### ISSUE TITLE
"Organize Imports" code action for TypeScript does not delete unused imports

### ISSUE THREAD

**Issue by micthiesen** [zed-industries/zed#11017]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The code action `"source.organizeImports"` is supposed to both sort imports and also remove unused imports. Compared to the `"source.sortImports"` code action which only sorts imports. [See here](https://code.visualstudio.com/updates/v1_57#_sort-imports-source-action).

To reproduce, create a TS file and import something that isn't used. Select "Organize Imports". The unused import is not removed.

### Environment

Zed: v0.132.2 (Zed)
OS: macOS 14.1.2
Memory: 32 GiB
Architecture: aarch64

Also: `"typescript": "^5.3.3"`

### If applicable, add mockups / screenshots to help explain present your vision of the feature

When chosen from the context menu, "Organize Imports" successfully sorts imports but it doesn't remove unused imports:
![Capture 2024-04-25 at 16 21 03](https://github.com/zed-industries/zed/assets/589613/4228df38-1ab6-48a6-80d4-616aba966d1b)

It also only sorts when used as a `"code_actions_on_format"` option:
![Capture 2024-04-25 at 16 23 36](https://github.com/zed-industries/zed/assets/589613/cd635a1f-9852-4058-9dd4-18afcc5eb239)

**Comment by micthiesen** [comment]
I can get around this by enabling the `"source.removeUnusedImports"` code action on format:

![Capture 2024-04-25 at 16 41 31](https://github.com/zed-industries/zed/assets/589613/a3bf22fd-6094-4ce5-a776-01f49bf1b603)

But I think there's a race condition between all the code actions that causes the imports to duplicate on save:

![Capture 2024-04-25 at 16 41 06](https://github.com/zed-industries/zed/assets/589613/02b5c339-d5e1-4aff-94e4-8fc60e09a9f4)

**Comment by AlbertoLanaro** [comment]
@micthiesen did you find any solution to the duplicated imports problem?

**Comment by micthiesen** [comment]
> @micthiesen did you find any solution to the duplicated imports problem?

No I'm back to VSCode 😭

**Comment by GustavoMelloGit** [comment]
Having the exact same problem and it is making me want to go back to vscode 😭
```json
{
  "theme": "Ayu Mirage",
  "ui_font_size": 13,
  "buffer_font_size": 13,
  "format_on_save": "on",
  "formatter": {
    "code_actions": {
      "source.fixAll.eslint": true,
      "source.organizeImports": true,
      "source.removeUnusedImports": true
    }
  }
}
```

**Comment by thraizz** [comment]
For me just this works as a local `.zed/settings.json` in a react/tsx project:
```json
{
  "format_on_save": "on",
  "code_actions_on_format": {
    "source.removeUnusedImports": true,
    "source.addMissingImports": true,
    "source.fixAll.eslint": true,
    "sourceAll.organizeImports": true
  }
}
```

**Comment by eulke** [comment]
The comments added might be related to [this](https://github.com/zed-industries/zed/issues/13633)
It should be fixed in the tomorrow preview release

**Comment by respectTheCode** [comment]
Any updates on this? I am trying to make the switch to zed but this is kind of a deal breaker.

**Comment by notpeter** [comment]
I'm closing this as stale.  The `Organize Imports` action is provided by the language server, so if it is leaving duplicated or unused imports that would likely be an issue upstream.  Since this issue was filed Zed has also switched from typescript-language-server to vtsls by default for typescript so it may be that the implementation in the latter is better.

Thanks for reporting!

**Comment by ayyash** [comment]
hello? what does the last comment mean? is it now working or do we need specific setup? I tried the settings for typescript but it still does not work, any hints?
