### ISSUE TITLE
Zed Crashes After a minute or two on Windows 11

### ISSUE THREAD

**Issue by 1982FenceHopper** [zed-industries/zed#11192]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Once compiled for Windows 11, Zed crashes after a minute or two. I could be writing for example the settings file and it would randomly crash on me. Happened on both Release and Debug builds.

### Environment

Zed 0.134.0.0
Windows 11 22H2 22621.3447

Type: Laptop
Manufacturer: ASUS
Mode: TUF FX506HF
CPU: Intel Core i5-11400H
GPU1: Intel UHD Graphics
GPU2: NVIDIA GeForce RTX 2050
RAM: 32 GB
Storage: Intel 670P Series 512GB + Crucial P3 1TB

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/15155539/Zed.log)

**Comment by 1982FenceHopper** [comment]
Is there a temporary workaround for this fix, as I am really excited to use Zed for lightweight coding.

**Comment by kaljitism** [comment]
I have the same specs as the original comment, difference is - 16 GB RAM and i7. 

For me as well, Zed is closing without any working in the release build.

**Comment by MatinAniss** [comment]
This may have been fixed by https://github.com/zed-industries/zed/pull/11393
Could be closed if resolved, I haven't had any issues.

**Comment by kaljitism** [comment]
Give me a few hours, I will check and get back to you..

**Comment by skejeton** [comment]
Can confirm. Seemingly random crashes, for no any particular reason. Works fine if i just restart and do the same action.

**Comment by kaljitism** [comment]
Yes, I worked on it for couple of hours and it didn't crashed. 

Analysis Server seemed to work a bit slow compared to Android Studio. I was using Dart. 

Is there a way, I can define a local dart-sdk and LSP on my device?

**Comment by skejeton** [comment]
Nope, still crashes after a couple minutes. But I'm on Windows 10.

**Comment by superboxes** [comment]
Still crashes, windows 11

**Comment by 1982FenceHopper** [comment]
> Still crashes, windows 11
> 
> Edit: Fixed it by setting zed to use the main gpu and not an igpu through windows display settings.

Will try using dGPU.

**Comment by 1982FenceHopper** [comment]
Update: So far, Zed has not crashed once it has been set to use my dGPU (NVIDIA). I will check for another few minutes to see if it does, but if not, will close.

**Comment by 1982FenceHopper** [comment]
Fixed: Using a discrete GPU (Tested NVIDIA here) did indeed work in preventing the OUT_OF_POOL_MEMORY crash. Something is up with GPUI using iGPUs but dGPUs do indeed work fine. Closing Issue.

**Comment by skejeton** [comment]
That's a shame. Is there a plan to support iGPU's? I use a work laptop, it doesn't have anything fancy in it.

**Comment by skejeton** [comment]
It's much better now, crashes after maybe every half an hour, actually quite usable. I notice the memory spikes from 400Mb immediately to 3.5Gb after some random point. After that it keeps running on ~4gb until it crashes completely. I suspect it has to do with #10203

**Comment by xgfone** [comment]
Still crashes just like @skejeton 

```
Windows 11
Rustc: 1.78.0 (9b00956e5 2024-04-29)
Zed: main branch, f780504b, Thu Jun 13 01:41:25 2024 +0100
```

**Comment by xgfone** [comment]
Zed crashed, it may be because of `igvk64.dll`.

![image](https://github.com/zed-industries/zed/assets/2664392/96b88186-c71b-4077-b9ec-0bc67f68fdf6)

**Comment by skejeton** [comment]
@xgfone 
Should be fixed when they update `blade`: https://github.com/kvark/blade/commit/845cdadbfe78b07a3f2b53af105cb497263b9cc4

**Comment by xgfone** [comment]
@skejeton tks, I re-compile zed later.

**Comment by xgfone** [comment]
I re-compiled zed with https://github.com/kvark/blade/commit/845cdadbfe78b07a3f2b53af105cb497263b9cc4, which has solved two bugs:
- The memory leak
- Zed crashes

So, hope Zed main branch updates `Cargo.toml` to https://github.com/kvark/blade/commit/845cdadbfe78b07a3f2b53af105cb497263b9cc4
