### ISSUE TITLE
Linux .desktop file improvements

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#12707]
### Check for existing issues

- [X] Completed

### Describe the feature

* [ ] It would be nice if the `Exec` line [accounted for passing files or URLs as arguments](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables) (so "Open With... > Zed" works properly, and [for registering as a handler for `https://zed.dev/channel/*`-URLs](https://unix.stackexchange.com/questions/497146/create-a-custom-url-protocol-handler)). Looks like there is already some preparatory code for this but it's not being used. 
* [ ] The file name of the .desktop file [MUST match the wayland app id](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#file-naming) for it to get correctly associated with application windows. 

EDIT: incorporated clarifications from @ReillyBrogan . StartupWMClass is not needed if the wayland app id (and therefore the file name) is identical to the WM_CLASS on X11. This is already the case, so no action is needed on that front.

**Comment by Moshyfawn** [comment]
I seem to remember the `app_id` proposal that was resolved in #10909. Does this satisfy your second point?

**Comment by ReillyBrogan** [comment]
It seems that you are a bit mistaken about how some of the .desktop FreeDesktop standards work.

> The 2nd point is about also having that app id stated in the .desktop file.

The `StartupWMClass` is ONLY for the X11 window class (it even has `WMClass` in the name which is an X11-only concept). If the Wayland appId and the X11 resource class are different then the .desktop file should be named after the Wayland app_id and the `StartupWMClass` should be the X11 resource class to be compliant with the standards.

The name of the .desktop file MUST match the Wayland appId sans the .desktop suffix. If the Wayland appId is `dev.zed.Zed` then the .desktop filename MUST be `dev.zed.Zed.desktop`. This is an explicit part of the FreeDesktop standards.

If the Wayland appId and the X11 resource class are the same then the `StartupWMClass` can be omitted from the .desktop file.

You may be using GNOME desktop which adds the value of the `StartupWMClass` field to the search path for matching Wayland windows via their appId. This is technically non-compliant with the FreeDesktop standards but it does some windows matched that would otherwise not be due to packaging mistakes which is why they did it. No other window manager or compositor implements this behavior. Frankly it's a mistake that has harmed the ecosystem as people see apps that are correctly matched on GNOME that don't work on Plasma or other DEs/WMs who then think that there is an issue with the other DE/WM when they should be reporting it to the app developers/package maintainers. If it's fixed in a compliant way it works for ALL Wayland DEs/WMs, instead of only working on GNOME.

**Comment by jansol** [comment]
Ooh, thanks for the clarification @ReillyBrogan !

**Comment by archerallstars** [comment]
This issue is still happening with GNOME.

Unless I manually specify `dev.zed.Zed` as the `StartupWMClass` in the desktop file, Zed shows no icon in the opening window.

Zed 0.196.6 (the standard installation method - `curl -f https://zed.dev/install.sh | sh`)
GNOME 48

**Comment by ReillyBrogan** [comment]
> This issue is still happening with GNOME.
> 
> Unless I manually specify `dev.zed.Zed` as the `StartupWMClass` in the desktop file, Zed shows no icon in the opening window.
> 
> Zed 0.196.6 (the standard installation method - `curl -f https://zed.dev/install.sh | sh`) GNOME 48

You need to rename the desktop file to `dev.zed.Zed.desktop`.

**Comment by archerallstars** [comment]
@ReillyBrogan 

Yes, I could do that also, but I would rather not to, as I install Zed, along with other dev tools in a container called `dev-dbx` (a Distrobox container). So, my desktop file for Zed is `dev-dbx-dev.zed.Zed.desktop`.

I think using the `StartupWMClass` is a more standard way to deal with desktop file on Linux, as it works on all systems, e.g. on immutable systems where apps are likely to be installed in a container.

MS Visual Studio Code does this also: https://github.com/microsoft/vscode/blob/fa99427534301606eb84c30cd8f7701ac2c35f90/resources/linux/code.desktop

**Comment by jansol** [comment]
If 3rd party packagers want to break things by [going against the spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/file-naming.html) they can also take care of fixing/working around said breakage.

> I think using the StartupWMClass is a more standard way to deal with desktop file

[it's not, it's an optional, X11-specific key](https://specifications.freedesktop.org/desktop-entry-spec/latest/recognized-keys.html) GNOME simply happens to handle it in a custom way on Wayland

**Comment by archerallstars** [comment]
@jansol 

I know full well about the spec. But I'm talking about the reality here:

1. GNOME is happened to be the default DE on Ubuntu and Fedora (and its downstream like RHEL), that are probably the most used Linux distro out there. So, having things break on GNOME, like it or not, is contrary to good user experience.
2. This is not a specific GNOME issue either. See KDE for example: https://bugs.kde.org/show_bug.cgi?id=466599 
3. `StartupWMClass` doesn't break anything on Wayland. To the contrary, it makes things work properly on the two most used/major DE on Linux, GNOME and KDE.
4. I would argue that the spec is not having a good design overall, as it will break with the container. You simply can't expect the app's desktop file to have the specific name in this case.

**Comment by morganastra** [comment]
Hi, I was helpfully pointed to this conversation from a PR I made attempting to also address the missing icon issue.

I wanted to add my observation that my distribution (Manjaro) is correctly installing the .desktop file as `/usr/share/applications/dev.zed.Zed.desktop`, so apparently that is not a complete solution to the missing icon issue. In my case I'm using KDE Plasma, on X11.

Adding the `StartupWMClass` field does fix the issue for me. It seems that it doesn't hurt in any cases and does help in some which may be a good reason to include it in the `zed.desktop.in` file, even if it "shouldn't" technically be necessary. If there's another solution that would also fix this in a comprehensive way I'd love to hear it - I just want a nice zed icon in my task switcher!

**Comment by ReillyBrogan** [comment]
> Hi, I was helpfully pointed to this conversation from a PR I made attempting to also address the missing icon issue.
> 
> I wanted to add my observation that my distribution (Manjaro) is correctly installing the .desktop file as `/usr/share/applications/dev.zed.Zed.desktop`, so apparently that is not a complete solution to the missing icon issue. In my case I'm using KDE Plasma, on X11.
> 
> Adding the `StartupWMClass` field does fix the issue for me. It seems that it doesn't hurt in any cases and does help in some which may be a good reason to include it in the `zed.desktop.in` file, even if it "shouldn't" technically be necessary. If there's another solution that would also fix this in a comprehensive way I'd love to hear it - I just want a nice zed icon in my task switcher!

Have you actually taken a look at what the resource/wm class is being set to? Because if it's not matching the icon then it's not being set properly. It should be `dev.zed.Zed`.

**Comment by morganastra** [comment]
It is:

```
> xprop WM_CLASS
WM_CLASS(STRING) = "dev.zed.Zed", "dev.zed.Zed"
```

**Comment by ReillyBrogan** [comment]
> It is:
> 
> ```
> > xprop WM_CLASS
> WM_CLASS(STRING) = "dev.zed.Zed", "dev.zed.Zed"
> ```

Actually, use the kwin debug console. Hit `Alt+F2`, type in "Kwin debug" until it appears, and then expand X11 windows and find the zed window. The property that Plasma specifically matches on is `resourceName`. So long as there is a desktop file named `$resourceName.desktop` somewhere in `/usr/share/applications` it will be matched against and display the icon specified in that file. If that still doesn't seem to be the case make sure you don't have a conflicting file in your flatpak directories (probably `/var/lib/flatpak/exports/share/applications` or `$HOME/.local/share/flatpak/exports/share/applications`), or in your local home folder (`$HOME/.local/share/applications`)

**Comment by morganastra** [comment]
Good to know. `resourceName` is indeed  `dev.zed.Zed`.

<img width="591" height="580" alt="Image" src="https://github.com/user-attachments/assets/44bd7398-3056-4a58-8419-b20bd70d4fae" />

As I mentioned above, zed's .desktop is also correctly installed as `/usr/share/applications/dev.zed.Zed.desktop`.

This is the `zed` package straight from the Manjaro  `extra` repository (which for `zed` is just a mirror of the Archlinux package).  I've never installed zed any other way, so there's no conflicting desktop file in my `~/.local/share/applications` or anything from flatpak.

Just to be precise, I can confirm that doing the following steps fixes it and makes the icon appear correctly:

* add `StartupWMClass=dev.zed.Zed` to the file `/usr/share/applications/dev.zed.Zed.desktop`
* run `kbuildsycoca5 --noincremental` 
* restart zed

**Comment by morganastra** [comment]
Out of curiosity I took a look at the other .desktop files I have installed on my system. A few dozen do have `StartupWMClass` set (including browsers, other graphical text editors/IDEs, every electron app I have installed), but there are a number of applications that do get their icons set correctly that don't have that line. As an arbitrary example, one of the shortest .desktop files I have is `/usr/share/applications/org.naev.Naev.desktop`. Its icon is set correctly.

```
[Desktop Entry]
Type=Application
Name=Naev
Comment=2D action/rpg space trading combat game
Comment[de]=2D Weltraum Action-/Rollenspiel mit Handels- und Kampfelementen
Comment[ja]=2Dアクション/RPG 宇宙交易戦闘ゲーム
Icon=org.naev.Naev
Exec=naev
Categories=Game;AdventureGame;
```

One thing I noticed anecdotally is that the `Icon` is almost always named the same thing as the desktop file (as it is above). On a hunch I copied `/usr/share/icons/zed.png`  to `dev.zed.Zed.png` and updated the `Icon` entry in the .desktop file accordingly... unfortunately that didn't work. I wonder what else we're missing?

**Comment by ReillyBrogan** [comment]
@morganastra I downloaded the Arch package from a mirror and took a look inside. Yes, the icon is installed incorrectly. It should be installed to `/usr/share/icons/hicolor/512x512/apps/zed.png` instead of where it is.

https://specifications.freedesktop.org/icon-theme-spec/latest/#directory_layout
