### ISSUE TITLE
Remote Dev: Formatting on save still happens when disabled

### ISSUE THREAD

**Issue by 0x5b62656e5d** [zed-industries/zed#20024]
### Description

Even though "format on save" is disabled in user settings, saving a file in a remote environment still formats the file.

1. Disable formatting on save in user settings (`"format_on_save": "off"`)
2. Connect to remote/ssh
3. Create a JS file
4. Add some poorly indented code (or "unformatted" code)
5. Save file

### Environment

Macbook Pro M3, Sequoia 15.1
Remote host: Raspberry Pi 4B, Debian GNU/Linux 12 (Bookworm)

**Comment by 0x5b62656e5d** [comment]
[Zed.log](https://github.com/user-attachments/files/17587835/Zed.log)
Was not able to upload log when submitting the issue for some reason

**Comment by exe-dealer** [comment]
in my case it helped to set `"format_on_save": "off"` in server settings file

**Comment by 0x5b62656e5d** [comment]
Even if I don't have a server settings file, it still should not format on save no? Based on local user settings?

**Comment by jameskozlowskimb** [comment]
I have run into the same issue when there is no config file on the remote. If I copy my config to the remote system then it works correctly. I would expect to not need to do this

**Comment by ConradIrwin** [comment]
Hmm. We should fix this. At one point we used to sync all your local settings to the remote, but that caused problems for people who have language-server specific configuration.

I think we need to figure out which settings need to be synced more granularly and upload those; probably all formatting related things (like indent size, etc.); Also `allow_binary_downloads` when we ship that. 

Any others that are top of mind?

**Comment by exe-dealer** [comment]
I think that root problem in case of 'format_on_save' is that it is on by default. It corrupted all my uncomitted changes when i decided to try zed editor on my pet project.

**Comment by justinmichaud** [comment]
> I think that root problem in case of 'format_on_save' is that it is 'on' by default. It corrupted all my uncomitted changes when i decided to try zed editor on my pet project.

Just my 2 cents, I totally agree. This bug bit me as well. It would be nice to have the option to disable this setting based on the style guides of the repo.

**Comment by aaronbuckner** [comment]
This problem was still valid as of last week. Very confusing. On Jun 11, 2025, at 14:07, github-actions[bot] ***@***.***> wrote:﻿github-actions[bot] left a comment (zed-industries/zed#20024)
Hi there! 👋
We're working to clean up our issue tracker by closing older issues that might not be relevant anymore. If you are able to reproduce this issue in the latest version of Zed, please let us know by commenting on this issue, and we will keep it open. If you can't reproduce it, feel free to close the issue yourself. Otherwise, we'll close it in 7 days.
Thanks for your help!

**Comment by jameskozlowskimb** [comment]
Yes, this issue is still present. This setting needs to be copied over to the remote host. I am working around this by manually copying my settings file to the remote host.

**Comment by KorigamiK** [comment]
> Yes, this issue is still present. This setting needs to be copied over to the remote host. I am working around this by manually copying my settings file to the remote host.

Thanks, this is a workaround which works reliably for now. 

```sh
echo '{ "format_on_save": "off" }' > ~/.config/zed/settings.json
```

**Comment by JuncongHe** [comment]
when I tried to config `terminal` in remote server, I got `Property terminal is not allowed` (while it's ok in local setting). Is that a bug or a feature? Because I need the remote terminal to correctly identify my `.venv` and I don't think there's a way doing so without a proper setting.
