### ISSUE TITLE
rust-analyzer: Failed to load workspaces.

### ISSUE THREAD

**Issue by feelingsonice** [zed-industries/zed#21762]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The `rust-analyzer` provided by from my `PATH` always fails to run. Yet when I run it manually via the command line it works fine. 

Zed then default to its own `rust-analyzer` but this behavior isn't ideal.

<img width="448" alt="Screenshot 2024-12-09 at 12 11 35 PM" src="https://github.com/user-attachments/assets/1f9dc737-f765-4257-8eed-08db6360dff6">

### Environment

Zed: v0.164.2 (Zed)
OS: macOS 15.1.1
Memory: 96 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Running `which rust-analyzer` gives:`/Users/<USER>/.cargo/bin/rust-analyzer`

Running a command like `rust-analyzer --version` gives `rust-analyzer 1.83.0 (90b35a62 2024-11-26)`.

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
2024-12-09T12:08:23.690352-08:00 [INFO] attempting to start language server "rust-analyzer", path: "/Users/<USER>/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs", id: 10
2024-12-09T12:08:23.690931-08:00 [INFO] found rust-analyzer in PATH. trying to run `rust-analyzer --help`
2024-12-09T12:08:23.691346-08:00 [ERROR] failed to run rust-analyzer after detecting it in PATH: binary: "/Users/<USER>/.cargo/bin/rust-analyzer": No such file or directory (os error 2)
2024-12-09T12:08:23.69272-08:00 [INFO] fetching latest version of language server "rust-analyzer"
2024-12-09T12:08:24.717056-08:00 [INFO] downloading language server "rust-analyzer"
2024-12-09T12:08:27.961329-08:00 [INFO] starting language server process. binary path: "/Users/<USER>/Library/Application Support/Zed/languages/rust-analyzer/rust-analyzer-2024-12-09", working directory: "/Users/bli/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src", args: []
2024-12-09T12:08:28.923515-08:00 [ERROR] Language server rust-analyzer (id 10) status update: Failed to load workspaces.
2024-12-09T12:08:28.923732-08:00 [ERROR] Language server rust-analyzer (id 10) status update: Failed to load workspaces.
```
</details>

**Comment by jansol** [comment]
Does the problem disappear if you run `rustup update && rustup component add rust-analyzer` **in your project directory** before launching zed? I've seen some recent-ish weirdness related to how rustup handles toolchain switching.

**Comment by feelingsonice** [comment]
> Does the problem disappear if you run `rustup update && rustup component add rust-analyzer` **in your project directory** before launching zed? I've seen some recent-ish weirdness related to how rustup handles toolchain switching.

I do that regularly, like once or twice every week.

I should also add that this problem seems random. I don't see it happening all the time and it will just randomly pop up as I'm editing my files. Sometimes restarting the LSP or zed makes it go away.

**Comment by feelingsonice** [comment]
@jansol this is still happening and very annoying. Any updates?

**Comment by jansol** [comment]
I don't have much time for my Rust projects, but I took a quick look just now and did not encounter the error. Then again I have a somewhat convoluted setup for rust-analyzer in an effort to pick up dependencies via nix:

```json
"rust-analyzer": {
      "binary": {
        "path": "/run/current-system/sw/bin/bash",
        "arguments": [
          "-c",
          "if [ -e flake.nix ]; then nix develop --command rust-analyzer; else rust-analyzer; fi"
        ]
      }
    }
```

It seems to also be fine if I leave out the logic and just make bash invoke rust-analyzer directly.

**Comment by feelingsonice** [comment]
I have a weird setup ass well 🤷 

```json
    "rust-analyzer": {
      "initialization_options": {
        "cargo": {
          "allFeatures": true,
          "buildScripts": {
            "rebuildOnSave": true
          }
        },
        "procMacro": {
          "enable": true
        },
        "checkOnSave": {
          "command": "clippy" // rust-analyzer.checkOnSave.command
        },
        "hover": {
          "references": {
            "enabled": true
          }
        },
        "imports": {
          "prefix": "crate",
          "preferPrelude": true,
          "granularity": {
            "enforce": true
          }
        },
        "inlayHints": {
          "bindingModeHints": {
            "enable": true
          },
          "closingBraceHints": {
            "minLines": 0
          },
          "closureCaptureHints": {
            "enable": true
          },
          "maxLength": null,
          "lifetimeElisionHints": {
            "useParameterNames": true,
            "enable": "skip_trivial"
          },
          "closureReturnTypeHints": {
            "enable": "always"
          }
        }
      }
    }
```

**Comment by s3bba** [comment]
I'm experiencing the same issue on Arch, rust-anayzer is installed by pacman. Here is the error I get:
`[2024-12-26T16:49:11+01:00 ERROR languages::rust] failed to run rust-analyzer after detecting it in PATH: binary: "/usr/bin/rust-analyzer": Not a directory (os error 20)`

And it's solved by the same solution mentioned in comments above of specifying binary location manually.

**Comment by danielgafni** [comment]
I am also using `rust-analyzer` with Nix. 

For me it's a different issue (with `pyo3`): 

```
pyclass: failed to build proc-macro
```

The version is 

```
rust-analyzer --version
rust-analyzer 2024-12-23
```

I also tried using `rust-analyzer-nightly` from [fenix](https://github.com/nix-community/fenix) but it didn't help.

**Comment by feluxe** [comment]
I have this error as well. I can run `rust-analyzer` from the command line in my project directory just fine. Zed seems to have trouble finding the right binary.

I use asdf version manager for installing rust.

I have this in my Zed log:


> cat ~/.local/share/zed/logs/Zed.log 
> ...
> 2025-03-06T19:33:38.763046152+01:00 [INFO] found rust-analyzer in PATH. trying to run `rust-analyzer --help`
2025-03-06T19:33:38.766070527+01:00 [ERROR] failed to run rust-analyzer after detecting it in PATH: binary: "/home/peter/.asdf/shims/rust-analyzer": Not a directory (os error 20)

**Comment by heksesang** [comment]
I am seeing this in my logs on Windows 11 with Zed 0.182.11 (installed through MSYS2):
```
2025-06-03T15:38:28.3376869+02:00 [INFO] downloading language server "rust-analyzer"
2025-06-03T15:38:28.3484176+02:00 [INFO] found rust-analyzer in PATH. trying to run `rust-analyzer --help`
2025-06-03T15:38:28.3486169+02:00 [ERROR] failed to run rust-analyzer after detecting it in PATH: binary: "D:\\pkgs\\cargo\\bin\\rust-analyzer.exe": Mappenavnet er ugyldig. (os error 267)
```

It seems similar to what others are reporting. In all cases it seems to result in a path which cannot be executed by Zed, but which works fine when executed manually through a terminal, although the error message is slightly different for each OS.

But it seems upgrading to 0.188.4 have resolved it in my case.

**Comment by kkew3** [comment]
The issue still persists in the latest version v0.190.6 (9a2dcbb) on macOS 12.7.6 Intel chip. With a freshly installed Zed (after deleting the Zed folder under `~/Library/Application Support`), and a simplest rust setup (`cargo new --bin test-zed`), the "Failed to load workspaces" popup appears *consistently*:

![Image](https://github.com/user-attachments/assets/7f2c29ac-7b7e-48ef-930d-a4448fe6335a)

Manually running `rust-analyzer` works otherwise just fine.

---

EDIT

The root cause on my side is that I have two copies of `cargo` installed, an outdated one from [`homebrew`](https://brew.sh) and a latest one from `rustup`; and Zed somehow uses the outdated `cargo` that is behind the latest one in `PATH`. After uninstalling `rust` formula from `homebrew`, the problem is resolved.

**Comment by sunerpy** [comment]
> Does the problem disappear if you run `rustup update && rustup component add rust-analyzer` **in your project directory** before launching zed? I've seen some recent-ish weirdness related to how rustup handles toolchain switching.

It worked for me...
