### ISSUE TITLE
"Error: no snapshots found for buffer" when renaming type in Go source file

### ISSUE THREAD

**Issue by ghost** [zed-industries/zed#23706]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

- I've opened a Go project with zed.
- gopls server is setup and have been working fine in general.
- When I try to rename a type, I get the error "no snapshots found for buffer 30064771180 and server 1"
- The type is renamed on the file itself, but all references in other files aren't updated.

### Zed Version and System Specs

Zed: v0.170.2 (Zed)
OS: Linux Wayland ubuntu 24.10
Memory: 15.2 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Plus Graphics (ICL GT2) || Intel open-source Mesa driver || Mesa 24.2.3-1ubuntu1

### If applicable, add screenshots or screencasts of the incorrect state / behavior

![Image](https://github.com/user-attachments/assets/72c74029-387f-4d4f-b777-7c164daa7b96)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
2025-01-27T12:09:45.264354688Z [INFO] ========== starting zed ==========
2025-01-27T12:09:45.292811727Z [INFO] Presentation support: "VK_KHR_wayland_surface"
2025-01-27T12:09:45.292901101Z [INFO] Presentation support: "VK_KHR_xcb_surface"
2025-01-27T12:09:45.292929411Z [INFO] Presentation support: "VK_KHR_xlib_surface"
2025-01-27T12:09:45.29296026Z [INFO] Enabling Vulkan Portability
2025-01-27T12:09:45.292986873Z [INFO] Enabling color space support
2025-01-27T12:09:45.322128652Z [INFO] Adapter: "Intel(R) Iris(R) Plus Graphics (ICL GT2)"
2025-01-27T12:09:45.322243319Z [INFO] No ray tracing extensions are supported
2025-01-27T12:09:45.324125743Z [INFO] perform;
2025-01-27T12:09:45.324212303Z [INFO] authenticate;
2025-01-27T12:09:45.324258653Z [INFO] Opening main db
2025-01-27T12:09:45.324310938Z [INFO] read_command;
2025-01-27T12:09:45.324429498Z [INFO] send_secondary_commands;
2025-01-27T12:09:45.324854319Z [INFO] new;
2025-01-27T12:09:45.324899595Z [INFO] socket reader;
2025-01-27T12:09:45.325134495Z [INFO] Opening main db
2025-01-27T12:09:45.325470802Z [INFO] keep_updated;
2025-01-27T12:09:45.327525135Z [INFO] Using git binary path: None
2025-01-27T12:09:45.364237226Z [INFO] No prompt template overrides directory found at /home/fornellas/.local/share/zed/prompt_overrides. Using built-in prompts.
2025-01-27T12:09:45.364816456Z [INFO] No prompt template overrides directory found at /home/fornellas/.local/share/zed/prompt_overrides. Using built-in prompts.
2025-01-27T12:09:45.37244792Z [INFO] extensions updated. loading 3, reloading 0, unloading 0
2025-01-27T12:09:45.374183854Z [INFO] activate is not implemented on Linux, ignoring the call
2025-01-27T12:09:45.375770976Z [INFO] perform;
2025-01-27T12:09:45.375822855Z [INFO] authenticate;
2025-01-27T12:09:45.375882172Z [INFO] read_command;
2025-01-27T12:09:45.376552549Z [INFO] socket reader;
2025-01-27T12:09:45.381765488Z [INFO] new;
2025-01-27T12:09:45.382316379Z [INFO] Opening main db
2025-01-27T12:09:45.383300815Z [INFO] keep_updated;
2025-01-27T12:09:45.38729641Z [INFO] set status on client 0: Authenticating
2025-01-27T12:09:45.387571316Z [INFO] perform;
2025-01-27T12:09:45.387603162Z [INFO] authenticate;
2025-01-27T12:09:45.387638985Z [INFO] read_command;
2025-01-27T12:09:45.38826594Z [INFO] socket reader;
2025-01-27T12:09:45.388812997Z [INFO] building git repository, `.git` path in the worktree: ".git"
2025-01-27T12:09:45.388921562Z [INFO] Using surface present mode MAILBOX
2025-01-27T12:09:45.38989251Z [INFO] Creating a descriptor pool for at most 16 sets
2025-01-27T12:09:45.390046229Z [INFO] Creating a descriptor pool for at most 16 sets
2025-01-27T12:09:45.39017694Z [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2025-01-27T12:09:45.393466632Z [INFO] new;
2025-01-27T12:09:45.394449842Z [INFO] keep_updated;
2025-01-27T12:09:45.401641185Z [INFO] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "Intel(R) Iris(R) Plus Graphics (ICL GT2)", driver_name: "Intel open-source Mesa driver", driver_info: "Mesa 24.2.3-1ubuntu1" }
2025-01-27T12:09:45.402206326Z [INFO] set status on client 248442: Connecting
2025-01-27T12:09:45.403761507Z [INFO] Using surface present mode MAILBOX
2025-01-27T12:09:45.403805726Z [INFO] Retaining current format: Bgra8UnormSrgb
2025-01-27T12:09:45.404077182Z [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2025-01-27T12:09:45.418172526Z [INFO] Using surface present mode MAILBOX
2025-01-27T12:09:45.418217482Z [INFO] Retaining current format: Bgra8UnormSrgb
2025-01-27T12:09:45.418423192Z [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2025-01-27T12:09:45.42845607Z [INFO] Using surface present mode MAILBOX
2025-01-27T12:09:45.428499828Z [INFO] Retaining current format: Bgra8UnormSrgb
2025-01-27T12:09:45.429778013Z [INFO] Using surface present mode MAILBOX
2025-01-27T12:09:45.429829995Z [INFO] Retaining current format: Bgra8UnormSrgb
2025-01-27T12:09:45.446841761Z [INFO] Opening main db
2025-01-27T12:09:45.510307177Z [INFO] using project environment variables from CLI. PATH="/home/fornellas/.cache/service-software-catalog-connector/GOROOT/go1.23.5.linux-amd64/bin:/home/fornellas/.cache/service-software-catalog-connector/kubeconform/linux/amd64/bin:/home/fornellas/.cache/service-software-catalog-connector/helm/v3.15.3/linux-amd64:/home/fornellas/.cache/service-software-catalog-connector/GOROOT/go1.23.5.linux-amd64/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/fornellas/.uc/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/fornellas/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
2025-01-27T12:09:45.535502965Z [WARN] unhandled message: Metadata(SupermavenMetadataMessage { dust_strings: None })
2025-01-27T12:09:45.61542037Z [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2025-01-27T12:09:45.713342853Z [INFO] set environment variables from shell:/bin/bash, path:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/fornellas/.cache/service-software-catalog-connector/GOROOT/go1.23.5.linux-amd64/bin:/home/fornellas/.cache/service-software-catalog-connector/kubeconform/linux/amd64/bin:/home/fornellas/.cache/service-software-catalog-connector/helm/v3.15.3/linux-amd64:/home/fornellas/.cache/service-software-catalog-connector/GOROOT/go1.23.5.linux-amd64/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/fornellas/.uc/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/fornellas/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
2025-01-27T12:09:45.987605849Z [INFO] add_connection;
2025-01-27T12:09:45.993042551Z [INFO] set status on client 248442: Connected { peer_id: PeerId { owner_id: 670, id: 3599856 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2025-01-27T12:09:46.078534506Z [INFO] Using surface present mode MAILBOX
2025-01-27T12:09:46.078591532Z [INFO] Retaining current format: Bgra8UnormSrgb
2025-01-27T12:09:46.137352885Z [INFO] Using surface present mode MAILBOX
2025-01-27T12:09:46.137392764Z [INFO] Retaining current format: Bgra8UnormSrgb
2025-01-27T12:09:46.30713171Z [INFO] Using surface present mode MAILBOX
2025-01-27T12:09:46.30717779Z [INFO] Retaining current format: Bgra8UnormSrgb
2025-01-27T12:09:56.947999875Z [INFO] Opening main db
2025-01-27T12:09:56.984200712Z [INFO] attempting to start language server "gopls", path: "/home/fornellas/src/service-software-catalog-connector", id: 1
2025-01-27T12:09:56.985342287Z [INFO] using project environment variables from CLI. PATH="/home/fornellas/.cache/service-software-catalog-connector/GOROOT/go1.23.5.linux-amd64/bin:/home/fornellas/.cache/service-software-catalog-connector/kubeconform/linux/amd64/bin:/home/fornellas/.cache/service-software-catalog-connector/helm/v3.15.3/linux-amd64:/home/fornellas/.cache/service-software-catalog-connector/GOROOT/go1.23.5.linux-amd64/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/fornellas/.uc/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/fornellas/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
2025-01-27T12:09:56.985742417Z [INFO] fetching latest version of language server "gopls"
2025-01-27T12:09:56.986352235Z [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(false) })
2025-01-27T12:09:57.43904943Z [INFO] downloading language server "gopls"
2025-01-27T12:09:57.447013067Z [INFO] starting language server process. binary path: "/home/fornellas/.local/share/zed/languages/gopls/gopls_0.17.1_go_1.23.5", working directory: "/home/fornellas/src/service-software-catalog-connector", args: ["-mode=stdio"]
2025-01-27T12:09:57.897979875Z [WARN] unhandled capability registration: Registration { id: "workspace/didChangeConfiguration", method: "workspace/didChangeConfiguration", register_options: None }
2025-01-27T12:10:15.822032036Z [INFO] Creating a descriptor pool for at most 16 sets
2025-01-27T12:10:15.853957928Z [INFO] Creating a descriptor pool for at most 16 sets
2025-01-27T12:10:15.887389152Z [INFO] Creating a descriptor pool for at most 256 sets
2025-01-27T12:10:15.903008077Z [INFO] Creating a descriptor pool for at most 256 sets
2025-01-27T12:10:19.497642642Z [ERROR] no snapshots found for buffer 30064771180 and server 1
```
</details>

**Comment by DoppleDankster** [comment]
I have the exact same issues since my update this morning.

NB: the server ID are not fix, from one update to the other the ID seems to change

**Comment by osiewicz** [comment]
The fact that server ID changes is a red herring; there's no guarantee of stability of those across Zed runs.

**Comment by bersace** [comment]
Hitting this too. Here is another scenario:

- open project
- try renaming a struct field -> triggers no snapshots
- rename a methods -> rename only in current buffer.

I also hit the *no snapshots* while renaming a method.

Didn't find how to workaround this. Quite annoying.

**Comment by bersace** [comment]
I may have found a workaround:

- list all references
- in multi-buffer, rename symbol
- works

**Comment by razcoen** [comment]
I am getting this when trying to rename a go package.

**Comment by fornellas** [comment]
@maxbrunsfeld it seems you've authored a good chunk of Go support for Zed, just a signal boost. Go support used to be absolutetly awesome, but since the past ~2 weeks, it became... somewhat disfunctional for its best feature, frequently.

**Comment by burdiyan** [comment]
I've been ignoring this issue for the past few weeks, but lately I need to refactor a lot, and now I'm suffering so much that I went on searching for solutions. Unfortunately couldn't find one yet.

**Comment by notpeter** [comment]
We're going to try and take a look at this next week during Quality Week.
Thanks for reporting.

**Comment by as-cii** [comment]
We just released a new version of Zed and Zed Preview that contains a fix for this. Can you double check this works now?

Thank you!

**Comment by bersace** [comment]
> We just released a new version of Zed and Zed Preview that contains a fix for this. Can you double check this works now?

0.173.11 works for me.

**Comment by petternett** [comment]
This is still very much an issue with .NET

**Comment by Yasaie** [comment]
Still happening
https://github.com/user-attachments/assets/07888768-4f86-4fc8-b7e0-aa0e2b99309f
