### ISSUE TITLE
Project Panel’s shortcut key incorrect in macOS View Menu

### ISSUE THREAD

**Issue by js-choi** [zed-industries/zed#28164]
### Summary

The shortcut key for the Project Panel in the View Menu on macOS displays “E” instead of “⇧⌘E” when using the default keymap.

Steps to trigger the problem:
1. Open a fresh installation of Zed on a Mac.
2. Turn on Vim mode (add `"vim_mode": true` to settings.json).
3. Click on the View Menu in the Menu Bar.
4. Look at the Project Panel command.

<img width="260" alt="Image" src="https://github.com/user-attachments/assets/4c16c6d6-ab50-4057-93e7-b8f7255b268a" />

Actual Behavior:
The View Menu displays “E” as the shortcut key of the Project Panel command.

Expected Behavior:
The View Menu displays “⇧⌘E” as the shortcut key of the Project Panel command.

Note: Overriding keymap.json causes the View Menu to display that keymap’s correct shortcut.

### Zed Version and System Specs

Zed: 0.184.10
OS: macOS 15.3.1
Memory: 16 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
![Image](https://github.com/user-attachments/assets/6bcab12b-5194-4462-98b1-a4c8218684ce)

With every settings and keybinding commented out, I did `zed --uninstall` and `curl -f https://zed.dev/install.sh | ZED_CHANNEL=stable sh` then.

I see this in Zed Stable now, so assuming the issue is fixed.

Let me know if it's still reproducible somehow with the extra details.

**Comment by js-choi** [comment]
@SomeoneToIgnore: I can confirm that, for Zed 0.184.10 on macOS 15.3.1, starting the application with a blank keymap.json displays the correct panel keybindings in the View Menu.

However, there is now a new bug in the displayed keybindings:

1. Start Zed.
2. Edit keymap.json to override the panel bindings and save—e.g.:
   ```
   [
     {
       "context": "Workspace",
       "bindings": {
         "shift-cmd-b": "git::Branch",
         "cmd-alt-e": "project_panel::ToggleFocus",
         "cmd-alt-g": "git_panel::ToggleFocus",
         "cmd-alt-b": "outline_panel::ToggleFocus",
         "cmd-alt-c": "collab_panel::ToggleFocus"
         // "shift shift": "file_finder::Toggle"
       }
     }
   ]
   ```
3. Check the View Menu. The keybindings for the panels are correctly changed.
4. Clear keymap.json and save again.
5. Check the View Menu. The keybindings for the panels still show the new keybingings even though they were removed.

Should I open a new issue for this new bug?

**Comment by SomeoneToIgnore** [comment]
I'll reopen, would be great to rearrange the messages here so that the update goes to the description.

**Comment by js-choi** [comment]
@SomeoneToIgnore: Thanks, I’ve updated the original post with a new description.

**Comment by MrSubidubi** [comment]
> Let me know if it's still reproducible somehow with the extra details.

@js-choi Could it be that you decided against using Vim-mode in the meantime?

Anyway, setting `"vim_mode": true` should make the original issue still reproducible.

**Comment by js-choi** [comment]
@js-choi: It looks like I made a silly mistake. I commented out all the lines in keymap.json, which was interpreted by Zed’s JSON parser as invalid JSON. That is why it failed to update the View Menu. Commenting out all lines except for the root object’s `{` and `}` made it update correctly. This issue seems to be truly fixed as far as I can tell. Sorry about the noise and thanks for checking.

**Comment by MrSubidubi** [comment]
@js-choi All good, I guessed something along these lines, stuff like this can happen. Happy to hear its working for you now!

Anyway, would you mind answering my questiong regarding whether you were using the vim-mode previously and are currently not using it anymore? 

From what I can tell, the root issue causing the behavior you initially reported actually still exists and the behavior you reported is still present for all users that have the vim-mode enabled.

**Comment by js-choi** [comment]
@MrSubidubi: I missed that part! Yes, the original bug still happens when Vim mode is on! Good spotting.
I’ve reopened the bug and edited the original post.
