### ISSUE TITLE
Zed lost data

### ISSUE THREAD

**Issue by shockme** [zed-industries/zed#29277]
### Summary

Zed lost data (conversations, settings, project history)

### Description
After upgrading to Flatpak Zed 0.182.11 I was presented with what seemed like a new install screen.
Project history is gone, AI conversations are gone (I looked on the disk in ~/.var/app/dev.zed.Zed/data/conversations/ and it's empty) and settings are gone.

Steps to reproduce:
1. upgrade Zed to 0.182.11 using `flatpak update`
2. start Zed
3. notice conversations, settings and project history are gone
4. switch to Roo 'cause you're pissed off

Expected Behavior:

No data loss

Actual Behavior:

Data loss

### Zed Version and System Specs

Zed: v0.182.11 (Zed) 
OS: Linux X11 ubuntu 22.04
Memory: 94.3 GiB
Architecture: x86_64
GPU: AMD Radeon RX 580 Series (RADV POLARIS10) || radv || Mesa 23.2.1-1ubuntu3.1~22.04.3

**Comment by MrSubidubi** [comment]
I think this was fixed in the newest release via #28952 and you should have all your configurations back.

**Comment by probably-neb** [comment]
Seems like this was resolved. Feel free to @-mention me here if you're still having issues after updating to the latest release

**Comment by shockme** [comment]
Indeed, after the update Zed restored the initial batch of conversations, but now the later conversations are missing!
I don't think loss of data is acceptable and this makes me unable to consider Zed as a serious tool on which I can rely for professional development.

**Comment by MrSubidubi** [comment]
@shockme You can recover your newest conversations by moving them from `$FLATPAK_XDG_DATA_HOME/conversations` (or something similar, I am not entirely sure about the name) to `$FLATPAK_XDG_DATA_HOME/zed/conversations`. Thus, they are not entirely gone, but won't be visible unless you choose to move these.

I can fully understand your frustration here. From my point of view it is questionable how this bug could make it to stable, given that it was reported and a fix available just one day after the preview release. I agree that things like this should not happen, especially for the stable release.

**Comment by MrSubidubi** [comment]
Hm this is weird and somewhat unexpected. Did you check by any chance whether there are any other `conversations` folders in your `$FLATPAK_XDG_DATA_HOME`? As mentioned, the issue arose due to these folders being misplaced. In theory, they should still exist, but potentially at the wrong locations, so there might be two directories at different locations.

Just to check, your current conversations are still present in Zed, right?

**Comment by shockme** [comment]
Yes, my current conversations are still present in Zed and in `~/.var/app/dev.zed.Zed/data/zed/conversations/`, but `~/.var/app/dev.zed.Zed/data/conversations/` is empty. My understanding is that the "intermediate" conversations should have been there.

**Comment by MrSubidubi** [comment]
Yep that was my understanding as well. Just re-checked the code and that's what I would also have guessed.

Unfortunately, then I am also out of ideas for this one, sorry that I cannot help you here any further. If you like, you can probably ping @\probably-neb and ask him whether he has an idea where the conversations are and how you can recover them.

Thanks for bearing with me and trying out everything I threw at you, sorry though that wasn't enough 😅

**Comment by shockme** [comment]
@MrSubidubi is it possible that the location has been changed from the `conversations` dir to an `.mdb` file?

**Comment by MrSubidubi** [comment]
@shockme Yes! That is a really good call and nice find!

It seems this here might be relevant:

https://github.com/zed-industries/zed/blob/bad21c247b70256c0d2fe6611ac9a0c6fab85745/crates/agent/src/thread_store.rs#L884

or this

https://github.com/zed-industries/zed/blob/bad21c247b70256c0d2fe6611ac9a0c6fab85745/crates/prompt_store/src/prompt_store.rs#L33

Do you have either of these?

**Comment by shockme** [comment]
@MrSubidubi yes, I have `threads/threads-db.1.mdb` in both locations:

```
$ ls ~/.var/app/dev.zed.Zed/data/threads/threads-db.1.mdb/
data.mdb  lock.mdb
$ ls ~/.var/app/dev.zed.Zed/data/zed/threads/threads-db.1.mdb/
data.mdb  lock.mdb
```

**Comment by MrSubidubi** [comment]
@shockme Nice, at least. 

Afterwards, it sadly might get a bit tedious: These files are LMDB databases of your threads, Zed uses https://docs.rs/heed/latest/heed/ to manage these (although there will be wrappers for other languages I believe). You would have to open both databases and merge their contents in the `zed/threads`. See

https://github.com/zed-industries/zed/blob/c089602cb1b2574f685db231c1eb75155dfe2bd7/crates/agent/src/thread_store.rs#L894-L914

for how these are initially loaded. 

Threads are stored as encoded bytes, see

https://github.com/zed-industries/zed/blob/c089602cb1b2574f685db231c1eb75155dfe2bd7/crates/agent/src/thread_store.rs#L854-L860

You would then have to extract the contents from the wrongly placed database and merge them in the new one. I am not sure whether there are some good tools to do such things, since my knowledge there is rather nonexistant. I would leave this up to you, but feel free to ping me if you have any other question.

**Comment by shockme** [comment]
@MrSubidubi thank you for your time, however it sounds quite involved and time consuming and at this point it doesn't make sense for me to spend the extra time.

**Comment by MrSubidubi** [comment]
@shockme That was my thinking as well, sad to see though. You are welcome, thanks for providing all the information. Have a nice day 😃
