### ISSUE TITLE
Zed Preview can't load environment variables

### ISSUE THREAD

**Issue by rejahn** [zed-industries/zed#32445]
### Summary

Zed (Preview) fails to load environment variables 

### Description

After updating ZED to 0.190 (currently on 0.190.3) on Ubuntu 24.04 and Fedora 42, I am getting every time when I launch zed a warning, that my environment variables couldn't be launched. I have tested so far 3 repositories.

Steps to reproduce:
1. Open ZED Preview
2. See at the bottom the warning that environment couldn't be loaded

**Expected Behavior**: No warnings regarding environment variables
**Actual Behavior**: warnings regarding environment variables

### Log

[Zed.log](https://github.com/user-attachments/files/20670474/Zed.log)

![Image](https://github.com/user-attachments/assets/3b8de704-d25e-48e8-ba88-d5e157158b88)

### Zed Version and System Specs

Zed: v0.190.3 (Zed Preview) 
OS: Linux X11 ubuntu 24.04
Memory: 31.2 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1650 || NVIDIA || 535.230.02

**Comment by mosenturm** [comment]
See this discord thread: https://discord.com/channels/869392257814519848/1204679850208657418/1381919368237285387
Same for me. `zed cli` is working as expected.

**Comment by rejahn** [comment]
@mosenturm thanks for the heads up! `zed cli` works as expected for me as well. The warning comes when I open zed with the app menu

**Comment by notpeter** [comment]
Looks like something is happening when trying to parse the value of one of your environment variables.

```
2025-06-10T11:47:13+02:00 WARN  [home] invalid value
2025-06-10T11:47:13+02:00 ERROR [project::environment] Failed to load environment variables. See log for details
2025-06-10T11:47:13+02:00 ERROR [project::git_store] failed to get working directory environment for repository "/home/renan/repos/privat/dotfiles"
```

Here's the location in code:
https://github.com/zed-industries/zed/blob/0a8a60035c424114dac4d2ebbd6ad39dd8588104/crates/util/src/shell_env.rs#L118-L124

Sounds like there might be something unexpected in your environment when spawning from the GUI.

**Comment by mosenturm** [comment]
The difference between app and cli is when starting the cli, the (for example .bashrc)  env is always there from starting shell. Esp. $PATH additions are complete. When starting the app, idk which env is available. But the $PATH is not ready at starting time. The current build (6d9bcdb2af603e1a3eee2531b1721550322d8f8d) still has the problem.

**Comment by FelipeGaleao** [comment]
Using zed cli, everything ran smoothly for me as well — no issues at all.

**Comment by notpeter** [comment]
This error means that Zed is failing at parsing one of your environment variables.  There were changes in https://github.com/zed-industries/zed/pull/31799 in how Zed parsed parsed environment variables and one of values of your environment variables is triggering something unexpected.

Can you paste the results of `sh -c 'export -p'` (make sure to redact any secrets or sensitive env vars)?

**Comment by ConradIrwin** [comment]
Can someone who is seeing this problem upload the (redacted) content of running:
`sh -c "export-p"`. I don't need the full values, but I am interested in weird quoting (like variables containing control characters or quotes)

We fixed a bug where variables containing escape characters couldn't be parsed in 0.190.4; but I think there are more bugs lingering here.

In the short term we may be able to fix things so that we don't fail if one var can't be parsed; but we should move to a world where we don't have to parse the output (it turns out it is not as standardized as it sounds like it should be!).

cc @haruleekim / @WeetHet

**Comment by mosenturm** [comment]
Here is my env.

[myenv.txt](https://github.com/user-attachments/files/20694833/myenv.txt)

**Comment by rejahn** [comment]
Here comes mine as well: [env.txt](https://github.com/user-attachments/files/20696757/env.txt)

Thanks for taking a look at it!

**Comment by notpeter** [comment]
> @mosenturm Here is my env. [myenv.txt](https://github.com/user-attachments/files/20694833/myenv.txt)

Oh I think it could be this:
```
export COMP_WORDBREAKS=' 	
"'"'"'><=;|&('
```
That's space, tab, newline and a bunch of single quote characters which are non-escaped.

There is some discussion in https://github.com/zed-industries/zed/pull/32404.  I'm going to take a crack and replacing the env var parsing code with something else.

**Comment by mosenturm** [comment]
`echo $COMP_WORDBREAKS` gives 
`"'><=;|&(` which looks ok.
It must be a parsing issue.

**Comment by notpeter** [comment]
Ok, so I figured out what @mosenturm's shell is doing.
Using double quotes this would be `" \t\n\"'><=;|&("`
but because we're using single quotes it becomes:
`' \t\n"'` `"'"` `'><=;|&('`
(tab/newline shown escaped and spaces added for clarity)
Which is three chunks: a single quoted string, a double quoted `'`, and a single quoted string.
🙃 

---

And @rejahn I think is this one for you:
```
FZF_CTRL_T_OPTS=$'\n  --walker-skip .git,node_modules,target\n  --preview \'bat -n --color=always {}\'\n  --bind \'ctrl-/:change-preview-window(down|hidden|)\''
```
Which I believe was fixed by https://github.com/zed-industries/zed/pull/32404 and should be available in today's preview and stable.

**Comment by rejahn** [comment]
Zed can now parse correctly the environment variables from my fedora environment from above. However, after upgrading zed preview to the latest version (0.191.0) in my other ubuntu machine, the issue is still here. I assume the variable `FZF_CTRL_R_OPTS` is once again making some trouble.

Here are the ubuntu environment variables for  further debugging (if necessary):
[ubuntu_myenv.txt](https://github.com/user-attachments/files/20708402/ubuntu_myenv.txt)

**Comment by mosenturm** [comment]
>  variable `FZF_CTRL_R_OPTS` is once again making some trouble.
 
That's right. It is the same escaping like for `COMP_WORDBREAKS ` from my env. I am on Ubuntu too. Fedora seems to be different.
