### ISSUE TITLE
Debugger: Terminal becomes non-interactive with NestJS/Jest/vitest watch mode after first run

### ISSUE THREAD

**Issue by andreasvh-conceto** [zed-industries/zed#33101]
### Summary

The debugger terminal becomes not interactive anymore when running nestjs tests in watch mode. 

### Description

Steps to trigger the problem:

1. create a nestjs application or clone the following: `git clone git@github.com:andreasvh-conceto/nestjs-zed-debugging.git`, do `npm i` and open the project in zed
2. Go to package.json an start the debugging for script `test:watch` or `test:e2e:watch`
![Image](https://github.com/user-attachments/assets/35521aef-8f15-407a-a1c9-a136b13c3181)
3. Alternative way to step 2 is to press `F4` (command: `debugger: start`) and  run one of the debug tasks:
![Image](https://github.com/user-attachments/assets/112e34f0-3262-4b17-8e7e-404a13523899)
4. If you pick the `Debug E2E Test` press `a` to run all tests. For `Debug Unit Test` it will run directly all specs
5. Now try to run again the test. Normally this is `enter` key in jest or try to interact with the watch mode:
![Image](https://github.com/user-attachments/assets/0c879d54-52cc-4f09-a5ac-7a63f062539e)

**Expected Behavior**:
I can still interact with the terminal in watch mode after the test passed/failed. Or at least i have the option to open an empty debug terminal like in vs code and type in my `npm run test:watch` commands, where it auto attaches to the node process and terminal is still interactive after test execution. In vs code in example i just open a debug terminal and type:
```bash
# unit test
npm run test:watch
# e2e test (where you normally you also hold some startup docker commands like database startup)
npm run test:e2e:watch 
# execute test but for a specific files, which contain `app` in the spec name
npm run test:watch app 
```
The vs code debugger directly attaches to the process, i can debug and still interact with the terminal after test execution.

**Actual Behavior**:
I can not type any command from the watch mode inside the terminal. I have to restart the test, which can result in waiting time. Especially if you execute some docker commands (`"pretest:e2e:watch"`": "docker compose up -d",
 i.e. to start a database before the test execution. 

### Zed Version and System Specs

Zed: v0.191.6 (Zed) 
OS: macOS 15.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by cole-miller** [comment]
Thanks for reporting this and providing a reproducer!

This happens because when we finish running your tests the first time, the JS debug adapter sends us the `Terminated` DAP event--per the spec:

> The event indicates that debugging of the debuggee has terminated. This does not mean that the debuggee itself has exited.

We respond to that event by tearing down the session (we send the `Disconnect` DAP request), which includes killing the debuggee, which is why you can't interact with it through the terminal anymore.

I'm not sure exactly what to do here. It seems like we'd be violating our end of the spec if we continued sending requests in the session after getting that event from the adapter, but in a case like this where the adapter sent us `runInTerminal`, we might be able to notice that the debuggee is still running and carry it over into a new session by re-attaching to it. I don't know how we'd decide when to do that, though. I'll try to figure out what VS Code does to get this to work.

**Comment by andreasvh-conceto** [comment]
@cole-miller 
Thanks for your answer. I completely understand, that you do not want to break the rules for the spec. But it would be great to have a good debugging workflow, which my colleagues and me currently dont have in zed, when running vitest/jest. At least i dont know how to archieve this. 

Let me give you a concrete workflow example in our team:

VsCode debugging vs Zed debugging

VsCode: 
1. i activate debug smart attach (F1 -> `Debug: Toggle Auto Attach`) or i open a new debug terminal 
2. i set the breakpoint and execute in the terminal i.e.: `npm run test:e2e:watch` or for a concrete file pattern `npm run test:e2e:watch sales-order` in order to execute spec files, where the filename contains `sales-order` - really smart and handy whatever file is opened in your IDE. 
3. the test starts: docker compose starts up testdatabase, test-eleastic etc. and starts up in watch mode
4. i set one specific test i want to debug to `only` if needed. The watcher directly reacts to this and debugger is still attached thanks to debug smart attach
5. THe breakpoint fires
6. first run of debugging was unsecccessful? No problem: In vitest, just press `r` for repeating or enter in jest
7. I have to change something in the code and watch mode directly triggers the repeat automatically? No problem
8. Iam in the breakpoint again in seconds
Note: We also debug e2e or integration tests, which do a full startup. Once you are in the watch mode you are glad not to wait the startup time again 

Zed:

1. i have to run my debug task 
2. I select the test
3. the test is executed and i go into breakpoint
4. after execution debugging first test execution terminal is not interactive anymore
5. i have one try to debug, otherwise i have to restart the complete task again (waiting time for docker composes etc.)
6. I also have to perform code changes and then restart the task again instead of reattaching to the next execution of the detected change. Watch mode is unusable for me when trying to debug
For step 1 i could integrate the current file dynamically, which is visible, but i much prefer step 2 from vsCode approach. Otherwise it is just time consuming.

Any idea here?
My personal opinion some kind of debug terminal in vs code or smart attach, would be a valid option to consider.

I prefer the zed editor much more, but this debugging in watch mode (we do regulary) is currently something i still to in vscode.

I would be delighted if you could find a solution here :) 

Thank you for your hard work!

**Comment by RemcoSmitsDev** [comment]
Hey @andreasvh-conceto, there is a really cool feature called **RunInTerminal** which allows you to run any node command inside the debug terminal. When your command gets executed, the JavaScript adapter will auto-attach itself to the node process of your program. This feature also allows you to stop the program and execute the program again + you should be able to interact with your program as expected.

See video as an example how to use the **RunInTerminal** feature. Small note, we just fixed a regression that was preventing you from typing in a command, because it was always showing the node REPL. See #33924, so you might have to wait before it's released. 

https://github.com/user-attachments/assets/62302d15-71e5-4ffb-9f90-5bc4e800d0a3

**Debug config (included by default)**
```json
{
  "label": "JavaScript debug terminal",
  "adapter": "JavaScript",
  "request": "launch",
  "type": "pwa-node",
  "cwd": "$ZED_WORKTREE_ROOT",
  "console": "integratedTerminal"
}
```

**Comment by andreasvh-conceto** [comment]
Thank you @RemcoSmitsDev  for this detailed explanation and this feature. This should fix my issue. I will wait until https://github.com/zed-industries/zed/pull/33924 is fixed and try again.

**Comment by RemcoSmitsDev** [comment]
Hey, our fix is out, you can try it with Zed Preview! Let me know if you find any issue with it.

**Comment by andreasvh-conceto** [comment]
Hi @RemcoSmitsDev ,
thanks for that fix implementation. It is a step in the right direction, but i have still issues debugging with my repo. Zed preview version:
```
Zed: v0.195.0 (Zed Preview) 
OS: macOS 15.5.0
Memory: 16 GiB
Architecture: aarch64
```

What i obeserved is the following - i recommend checking out the project. In VSCode it is directly working fine:
1. `git clone git@github.com:andreasvh-conceto/nestjs-zed-debugging.git` (if you ghave it already, get the newest changes i did)
2. `npm i`
3. In the project i added the debug.json with the debug config you provided under the name `My JavasScript debug terminal`.

Now i set a breakpoint inside `app.e2e-spec.ts`
<img width="531" height="259" alt="Image" src="https://github.com/user-attachments/assets/6e86c8dc-aba0-42bd-be45-5fd95d510ce0" />

Now i still run into the following issues:

## Issue 1: Unexpected crash with default debugging config
command `debugger:start` -> Select default `JavaScript debug terminal`

First issue:
```json
Tried to launch debugger with: {
  "request": "launch",
  "cwd": "/Users/<username>/dev/nestjs-zed-debugging",
  "console": "integratedTerminal",
  "sourceMaps": true,
  "pauseForSourceMap": true,
  "sourceMapRenames": true
}
error: debugger shutdown unexpectedly
```

## Issue 2: Using own Debug terminal task for e2e watch app still kills session after first time
command `debugger:start` -> Select my project specific `My JavaScript debug terminal` debug configuration

The terminal starts, type now:
`npm run test:e2e:watch app`

The breakpoint will fire, in the logs it tells me something, about not beeing able  reading the source map files. I am able to debug, but sounds weird.
```
Could not read source map for file:///Users/<username>/dev/nestjs-zed-debugging/node_modules/typescript/lib/typescript.js: ENOENT: no such file or directory, open '/Users/<username/dev/nestjs-zed-debugging/node_modules/typescript/lib/typescript.js.map'
Could not read source map for file:///Users/<username>/dev/nestjs-zed-debugging/node_modules/%40jridgewell/trace-mapping/src/trace-mapping.ts: ENOENT: no such file or directory, open '/Users/<username>/dev/nestjs-zed-debugging/node_modules/@jridgewell/trace-mapping/src/") at the end of the child file.'
```
If i proceed with the test, the erminal directly is killing the session.
```bash
Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press o to only run tests related to changed files.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.
[1]    24971 killed     npm run test:e2e:watch app
```

Iam unable to reexecute the test, just by pressing enter. I have to type `npm run test:e2e:watch app` again, BUT breakpoint does not fire from now on. I have to complete execute command `debugger:start` -> Select my project specific `My JavaScript debug terminal` again with a complete refreshed terminal.


## Issue 3: Debug session is still killed in watch mode in general
Same as issue 2, just with the `npm run test:e2e:watch` command without a specific file infix. 
 
command `debugger:start` -> Select my project specific `My JavaScript debug terminal` debug configuration
The terminal starts, type now:
`npm run test:e2e:watch`

press `a` for executing all tests and you will run into the breakpoint. Session directly killed again:
`Watch Usage: Press w to show more.[1]    29686 killed     npm run test:e2e:watch`

You have to reexecute the `debugger:start` command again.

I would be very grateful if you could look into the problem further.

Thanks and best regards 🙏

**Comment by RemcoSmitsDev** [comment]
Hey, thanks for testing it out and giving such a detailed description of the issues you are having. 

For **issue 1** could you share your debug adapter logs(RPC)? I cannot reproduce this.

For **issue 2/3** I know what the issue is, we are receiving `terminated` event for both the parent and child session. If we receive this event, we shut down the adapter processes, so re-attaching won't work what is expected. I think this is an issue on the JavaScript debug adapter side, that they send the terminated event even though the parent session should not be terminated. I will look into this and see if we can make a fix for it.

**Comment by andreasvh-conceto** [comment]
Thank you @RemcoSmitsDev  for your quick reply. Hope you will find a solution for issue 2/3.

I tried again issue 1. Directly after `debugger: start` -> `JavaScript default terminal` i opened the DAP Logs via command:
`dev: open debug adapter logs`

Debug Adapter Logs shows me the following:
node version is `v24.2.0`:

``` bash
stderr: Error: Unknown config: {"request":"launch","cwd":"/Users/<user>/dev/nestjs-zed-debugging","console":"integratedTerminal","sourceMaps":true,"pauseForSourceMap":true,"sourceMapRenames":true}

stderr:     at bp (/Users/<user>/Library/Application Support/Zed/debug_adapters/JavaScript/JavaScript_v1.102.0/js-debug/src/dapDebugServer.js:26:4382)

stderr:     at xa (/Users/<user>/Library/Application Support/Zed/debug_adapters/JavaScript/JavaScript_v1.102.0/js-debug/src/dapDebugServer.js:46:9364)

stderr:     at Og.boot (/Users/<user>/Library/Application Support/Zed/debug_adapters/JavaScript/JavaScript_v1.102.0/js-debug/src/dapDebugServer.js:100:8109)

stderr:     at Server.<anonymous> (/Users/<user>/Library/Application Support/Zed/debug_adapters/JavaScript/JavaScript_v1.102.0/js-debug/src/dapDebugServer.js:106:3664)

stderr:     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

```


```
Tried to launch debugger with: {
  "request": "launch",
  "cwd": "/Users/<user>/dev/nestjs-zed-debugging",
  "console": "integratedTerminal",
  "sourceMaps": true,
  "pauseForSourceMap": true,
  "sourceMapRenames": true
}
error: debugger shutdown unexpectedly
```

If you need further information, feel free to ask :)

**Comment by RemcoSmitsDev** [comment]
Thanks for the info! I think if you add `type = pwa-node` to your debug config, it should work.

**Comment by andreasvh-conceto** [comment]
okay, this is working, thanks. But only for my custom debug task.
```
  {
    "label": "My JavaScript debug terminal",
    "adapter": "JavaScript",
    "request": "launch",
    "type": "pwa-node",
    "cwd": "$ZED_WORKTREE_ROOT",
    "console": "integratedTerminal",
    "sourceMaps": true,
    "pauseForSourceMap": true,
    "sourceMapRenames": true
  }

```

Would it make sense to add `type= pwa-node` to the default task `JavaScript debug terminal`? Then it would work out of the box with default zed's debug task config.

**Comment by RemcoSmitsDev** [comment]
Yeah already have that change locally, will commit it with the other fixes.

**Comment by RemcoSmitsDev** [comment]
@cole-miller want to pair on the fixing the debug terminal issue. Inside the initial implementation this worked, but somewhere down the line it got broken. Already looked into it, because we get the terminated event for the root and child session, which seem to break this feature.

**Comment by andreasvh-conceto** [comment]
Hi @RemcoSmitsDev @cole-miller 
could it be that you already released a fix for part of that issue? At least i can see some improvements related to this issue in version:
```
Zed: v0.196.6 (Zed) 
OS: macOS 15.5.0
Memory: 16 GiB
Architecture: aarch64
```

Let me describe the recognized improvements and non expected behaviour related to this session killed issues. There are different behaviours depending if you are working inside a mono repo (with frontend and backend app) or not. I have now 2 repositories. I restructured the issues depending on the repository, so you can focus better on the issues per repo.

In any of these cases set the breakpoint in the `app.e2e-spec.ts` and one inside the `app.controller.spec.ts` to see if the breakpoint fires.

# 1 Normal App Repo
Repo: `git clone git@github.com:andreasvh-conceto/nestjs-zed-debugging.git`

Inside your terminal:
`cd nestjs-zed-debugging && npm i &&  zed .`

set the breakpoint in the `app.e2e-spec.ts` to see if the breakpoint fires

## 1a Success case - without pre and post scripts (fixed)
This error seems to be fixed in a simple scenario at least. I also added some command to clean and start a database container before the test started.  

`debugger:start` -> `JavaScript debug terminal` and then type the `npm run test:int:watch:success app` 
And also the whole watcher in a new/rerunned debug session:
`debugger:start` -> `JavaScript debug terminal` and then type the `npm run test:int:watch:success` -> press a to execute all jest tests

In both Docker container is started, debugger fires. Even if it finished, iam able to interact with the watch mode. And also if i perform code changes, it directly fires the breakpoint again for the next run. Brilliant :) 

## 1b Killed case with npm pre- and postscripts
The same case as the success case `2a`, but now it is a little bit more structured in  [Pre- and Post scripts](https://docs.npmjs.com/cli/v8/using-npm/scripts#pre--post-scripts).
```json
    "pretest:int:watch:kill": "npm run db:restart",
    "posttest:int:watch:kill": "npm run db:stop",
    "db:stop": "docker compose down -v",
    "db:start": "docker compose up -d",
    "db:restart": "npm run db:stop && npm run db:start",
```

`debugger:start` -> `JavaScript debug terminal` and then type the `test:int:watch:kill` 
 or `debugger:start` -> `JavaScript debug terminal` and then type the `test:int:watch:kill app` 
In this scenario the pretest script executes and when the docker command is finishing with success, it kills the session before the jest watcher started. I think it recognizes the pre script as the `main process` i want to debug. 

The debugger terminal output:
```bash
$ npm run test:int:watch:kill                                                                                                               
Debugger attached.

> nestjs-zed-debugging@0.0.1 pretest:int:watch:kill
> npm run db:restart

Debugger attached.

> nestjs-zed-debugging@0.0.1 db:restart
> npm run db:stop && npm run db:start

Debugger attached.

> nestjs-zed-debugging@0.0.1 db:stop
> docker compose down -v

Waiting for the debugger to disconnect...
[1]    13776 killed     npm run test:int:watch:kill
```

# 2 Mono Repo with front- and backend application
Repo: `git clone git@github.com:andreasvh-conceto/zed-debugging-monorepo.git`
Inside your terminal:
`cd zed-debugging-monorepo && npm i &&  zed .`

set the breakpoint in the `app.controller.spec.ts` to see if the breakpoint fires


## killed session after first run inside a mono repo
Set a breakpoint inside `app.controller.spec.ts`
`debugger:start` -> `JavaScript debug terminal` and then type the `cd backend && npm run test:watch app`
or `debugger:start` -> `JavaScript debug terminal` and then type the `cd backend && npm run test:watch` -> press `a` for executing all jest tests

The breakpoint fires, but after continuinng session gets killed after the first run.
```
Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press o to only run tests related to changed files.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.
[1]    7130 killed     npm run test:watch app
```

Fixing this will be definitely a game changer for my colleagues and me debugging with zed :) If you need something more feel free to ask :) 

Iam grateful for a solution in the future :)

**Comment by RemcoSmitsDev** [comment]
Hey @andreasvh-conceto, we fixed that the default configuration was failing due to a missing configuration key. But I haven't had the energy/time to more into the auto attach issue that does not allow you to re-attach multiple times. I'm thinking of creating an upstream issue on the `microsoft/vscode-js-debug` repo, but first want to see if it's something we are doing wrong. Will try to look into this more week or so, hope it's not too blocking for u.

Thanks again btw for the details about the issue you are having.

**Comment by andreasvh-conceto** [comment]
> Hey [@andreasvh-conceto](https://github.com/andreasvh-conceto), we fixed that the default configuration was failing due to a missing configuration key. But I haven't had the energy/time to more into the auto attach issue that does not allow you to re-attach multiple times. I'm thinking of creating an upstream issue on the `microsoft/vscode-js-debug` repo, but first want to see if it's something we are doing wrong. Will try to look into this more week or so, hope it's not too blocking for u.
> 
> Thanks again btw for the details about the issue you are having.

Hi @RemcoSmitsDev ,
thanks for your effort. Any Updates here on that issue, a plan B solution? It seems to be Microsoft is ignoring your created issue :(

**Comment by RemcoSmitsDev** [comment]
Hey @andreasvh-conceto, yeah havent looked it this issue for a while. But as you pointed out i also didnt get an reply back. So im waiting on that, Because i don't know wat to try to get it working as expected.

**Comment by andreasvh-conceto** [comment]
Hey, this bug is still present and for our team absolutely important to fix. Currently iam only able to debug efficently in vscode. docker compose up -d commands for integration test db startup will directly terminate after success (see one of the issues above) and unit test i can only debug a single time in watch mode.

I just hope somebody in the [blocking issue](https://github.com/microsoft/vscode-js-debug/issues/2258) will answer to the question so that this issue can be solved. For now i have to go with vscode in debug sessions.
