### ISSUE TITLE
Setting "terminal.shell" does not work on remote environment.

### ISSUE THREAD

**Issue by ealap** [zed-industries/zed#35226]
### Summary

Setting "terminal.shell" does not work on remote environment.

### Description

After a successful remote connection to my server and opening the terminal, it is still using the "system" shell for user instead of the `terminal.shell.program` which I set to `nu`. Locally, it works fine.

Steps to reproduce:
1. Set the terminal shell program
```jsonc
"terminal": {
  "shell": {
    "program": "nu"
  }
}
```
2. Connect to a remote machine.
3. Open zed-editor terminal.

**Expected Behavior**:
Remote development feature respects the `terminal.shell.program` setting.

**Actual Behavior**:
Remote terminal opens the program defined by $SHELL environment.

### Zed Version and System Specs

Zed: v0.196.6 (Zed) 
OS: Linux Wayland nixos 25.11
Memory: 27 GiB
Architecture: x86_64
GPU: AMD Radeon RX 7800 XT (RADV NAVI32) || radv || Mesa 25.1.6

**Comment by ealap** [comment]
My workaround for now is to manually call the shell I want. I cannot change the default shell to nushell yet because I have some tools that expects a POSIX-compliant shell.

**Comment by notpeter** [comment]
Similar to:
- https://github.com/zed-industries/zed/issues/29705

Where local language formatter settings are not get propagated to the remote.
Thanks for reporting.

**Comment by ealap** [comment]
Indeed, after copying my settings.json file over to the remote, it now uses nushell when open terminal! Thanks!

**Comment by ealap** [comment]
> Indeed, after copying my settings.json file over to the remote, it now uses nushell when open terminal! Thanks!

It seems this only works for Linux to Linux (or maybe for same OS only). I have tried Windows->Linux and MacOS-> Linux and it falls back to their default shell.

**Comment by alanxmay** [comment]
same issue

**Comment by corentinbettiol** [comment]
> Indeed, after copying my settings.json file over to the remote, it now uses nushell when open terminal! Thanks!

Hi, I tried to setup the `terminal` config on a remote environment, but all I got was this message when hovering it:

*Property terminal is not allowed.*

(I'm on Kubuntu, remote environment is a docker container running ubuntu)

**Comment by notpeter** [comment]
> _Property terminal is not allowed._

Are you putting this in project settings (.zed/settings.json) or in user settings (~/.config/zed/settings.json) because `terminal` is not valid in the former.

**Comment by alanxmay** [comment]
I'm facing the same issue. Steps to reproduce:  
1. Open a remote project on macOS, with the remote system running Ubuntu 22.04;  
2. Press Cmd+Shift+P to open server settings, where the settings file is located at `~/.config/zed/settings.json`.

<img width="928" height="752" alt="Image" src="https://github.com/user-attachments/assets/cf145c53-808f-4c0b-b22b-60b24cb370e5" />

**Comment by bytesiz3d** [comment]
Would love if this issue were fixed!

**Comment by sergeyk-bivial** [comment]
ended up putting this in `~/.zshenv`

```sh
if [[ -o interactive ]]; then
  exec /opt/homebrew/bin/fish
fi
```

Looking forward to a proper fix.

**Comment by steinemann** [comment]
It's a real blocker for me, as I cannot set fish as my default login shell.
OS: Windows
Zed 0.232.2 
Commit: 34f1025a77a17ae5401c9395b4f73536c6f76d6c
Version: 0.232.2+stable.229.34f1025a77a17ae5401c9395b4f73536c6f76d6c

**Comment by hrply** [comment]
still not work by setting ~/.config/zed/settings.json or $PROJECT_FOLD_PATH/.zed/settings.json
```
{
  "terminal":{
    "shell": {
      "with_arguments": {
        "program": "/home/hrply/.cargo/bin/codemux",
        "args": [--login]
      }
    }
  }
}
```

but can be particially solved by setting ~/.bash_profile
```
if [ -f ~/.bashrc ];
  then source ~/.bashrc;
fi
if [[ -n "$SSH_TTY" ]]; then
    exec zsh
fi
```

**Comment by quinn** [comment]
Just added this PR:

https://github.com/zed-industries/zed/pull/61451

This will read the remote user's zed config (e.g. `~/.config/zed/settings.json` on the remote host) and use that setting for the shell.
