### ISSUE TITLE
Zed is taking 3+ seconds to save a file, GIT panel not working

### ISSUE THREAD

**Issue by Hexacker** [zed-industries/zed#37100]
### Summary

SUMMARY_SENTENCE_HERE

### Description

I'm facing an issue while working on Zed, when I try to save a file, it takes more than 3 seconds to just save the changes.

Also, the Git panel, is not working.
I shared a video on Reddit

**Expected Behavior**: Immediate saving
**Actual Behavior**: Slow changes saving

https://github.com/user-attachments/assets/d204ba9d-38e1-44c7-aa63-04d26abf34ed

### Zed Version and System Specs

Zed: v0.201.5 (Zed) 
OS: macOS 15.6.1
Memory: 32 GiB
Architecture: aarch64

**Comment by Hexacker** [comment]
[Zed.log](https://github.com/user-attachments/files/22034786/Zed.log)

**Comment by SomeoneToIgnore** [comment]
1. It seems that Zed hits some odd state and traverses a lot of "external" directories, presumably all in `~/`:

> 2025-08-28T10:32:48-04:00 ERROR [worktree] error scanning directory "/Users/hexacker/Library/Containers/com.apple.STMExtension.iOSFiles/Data/Library/Calendars": Operation not permitted (os error 1)


>2025-08-28T19:42:59-04:00 INFO  [lsp] starting language server process. binary path: "/usr/local/bin/node", working directory: "/Users/hexacker", args: ["/Users/hexacker/Library/Application Support/Zed/prettier/prettier_server.js", "/Users/hexacker"]

Out of curiousity, do you have any symlinks in the project you open?

Git not working most probably is explained by this: Zed actively scans and logs projects across the entire home dir, initializing language servers and repositories, and so many git repos make it to loose any trace of the current one.

2. Given the
> 2025-08-28T19:35:40-04:00 INFO  [project::lsp_store] attempting to start language server "wakatime", path: "/Users/hexacker/Desktop/Work/Workleen/workleen", id: 1

logs, your workspace directory is in `~/Desktop/Work` which is not the same real FS as `~/Downloads` is: the sync operations there are extremely slow usually as it's a special, iCloud-synced directory.

--------------------

Does this all break if you move the project into a "normal" directory, e.g. `~/Downloads/` and re-run Zed on it?

**Comment by Hexacker** [comment]
Thanks for the replay @SomeoneToIgnore, I have moved the entire Work folder to my user folder, and everything fixed.

That's a weird issue for me, I used the same folder in Desktop for years on: VSCode, WebStorm, and Sublime Text, and I haven't faced this issue before.

**Comment by Hexacker** [comment]
Well, after a while, the Git issue back again, the slow issue is gone until now.

**Comment by SomeoneToIgnore** [comment]
Thank you for confirming.
Yes, this is not good at all, and we should fix it eventually.

Your issue splits into 2: https://github.com/zed-industries/zed/issues/35780 is for handling `~/` gracefully.
I suspect something else is in play, as it's very odd that you've opened a `~/Desktop/Work/project/` project but got the whole `~/` scanned.

The other one is file saving & peculiar FSes to tackle.

**Comment by Hexacker** [comment]
Well, after a while, the issue of slow saving back again right now. Now, it became really annoying to the point that made Zed useless, for real.

**Comment by Hexacker** [comment]
Another weird issue. I opened a NestJS project, it works flawlessly, fast saving and Git panel works just fine, I reopened the AdonisJS project, same, it's working just fine.

**Comment by Hexacker** [comment]
UPDATE:

I have uninstalled Zed completely, deleted every related file/folder that has a relationship with Zed, and reinstall it again, The issue was gone.

After installing some Themes and Icon Themes, the issue back again: VSCode Icons Theme and Catppuccin Icons, JetBrains New UI Icon Theme, I've tested all of them and the issue remains, I deleted them and the issue gone.

**Comment by Hexacker** [comment]
UPDATE:

After a while, the issue back again, and now, I have deleted every extension and get it back to the initial but the issue remain.

[Zed.log](https://github.com/user-attachments/files/22191683/Zed.log)

**Comment by xinxnm** [comment]
Any updates here? This is making Zed pretty unusable.

**Comment by Hexacker** [comment]
UPDATE:
Latest MacOS release.
Latest Zed release.

When running Zed from the terminal adding the `--foreground` param, everything works perfectly fine.

https://github.com/user-attachments/assets/a1b04ce5-698b-4feb-a2bc-4b33b0641902

**Comment by Hexacker** [comment]
UPDATE:

I spent the last days investigating about this issue, and fortunately, I've found the cause of this problem.

Explanation:
The first time I installed Zed back in 2023, at that time, I had an Intel based MBP. When I migrated to a MacStudio, I migrated everything to it, but under the hood, everything was working under Rosetta, not the correct release which must be the aarch64.

So for months, I was using the x86-64 version. It was working just fine, fast and reliable, but after the recent releases of Zed, the issue of slow saving and Git showed up.

After I migrated my Terminal to use the arch64, and all the apps I installed using brew, the issue gone and everything back to work perfectly fine now. Actually, I'm experiencing even faster experience 😎

**Comment by rambocode** [comment]
When running Zed from the terminal adding the --foreground param, everything works perfectly fine.

but when use zed.app it is slowly
