### ISSUE TITLE
Windows:  "command" not json encoded in mcp context server modal, fails with windows paths

### ISSUE THREAD

**Issue by adam-huganir** [zed-industries/zed#42692]
### Summary

When going to edit an existing MCP server, if the server command has any backslashes (or ostensibly any other non json compat character) it will not print valid json, and you will not be able to save the config again.

### Description
1. Open zed, and open the agent panel
2. Go into the agent settings
3. Add an mcp, replacing the content block for "some-mcp-server" with the below. for my case it was the jetbrains ide mcp that i was using to test with:
```json
{
  "some-mcp-server:" {
    "env": {
      "IJ_MCP_SERVER_PORT": "64342"
    },
    "command": "C:\\Users\\adam\\AppData\\Local\\Programs\\PyCharm Professional\\jbr\\bin\\java",
    "args": [
      "-classpath",
      "C:\\Users\\adam\\AppData\\Local\\Programs\\PyCharm Professional\\plugins\\mcpserver\\lib\\mcpserver-frontend.jar;C:\\Users\\adam\\AppData\\Local\\Programs\\PyCharm Professional\\lib\\util-8.jar;C:\\Users\\adam\\AppData\\Local\\Programs\\PyCharm Professional\\lib\\modules\\intellij.libraries.ktor.client.cio.jar;C:\\Users\\adam\\AppData\\Local\\Programs\\PyCharm Professional\\lib\\lib-client.jar;C:\\Users\\adam\\AppData\\Local\\Programs\\PyCharm Professional\\lib\\modules\\intellij.libraries.ktor.client.jar",
      "com.intellij.mcpserver.stdio.McpStdioRunnerKt"
    ]
  }
}
```
4. Hit configure server, and either wait until it times out, or escape out of it.
5. Click configure server on the newly created mcp.
6. You will see command is `"C:\Users\adam\AppData\Local\Programs\PyCharm Professional\jbr\bin\java"` (the string of the pathbuf)

**Expected Behavior**:

<img width="666" height="463" alt="Image" src="https://github.com/user-attachments/assets/8447dfb8-a61e-41d4-9771-3d3c1c31c9f9" />

**Actual Behavior**:

<img width="701" height="534" alt="Image" src="https://github.com/user-attachments/assets/740c4547-2bc9-4a02-ba82-92983d852575" />

It's an easy fix that should not have any side affects since it only affects this modal and invalid json would never be desirable here. we'll see what the tests say

### Zed Version and System Specs

Zed: v0.212.5 (Zed) 
OS: Windows 10.0.26100
Memory: 61.7 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 4090 || NVIDIA Corporation || 581.8 r580_92

**Comment by franciskafyi** [comment]
Just want to check...

What you pasted in is wrongly using ] vs } it seems and I'm getting this error on MacOS when trying to reproduce. 

<img width="565" height="482" alt="Image" src="https://github.com/user-attachments/assets/283d2b4d-ddd5-4ab5-bee2-1d0df864f2e7" />

Your screenshots don't show ] so maybe entirely unrelated! I'll ask the team to review the PR asap.

**Comment by adam-huganir** [comment]
> Just want to check...
> 
> What you pasted in is wrongly using ] vs } it seems and I'm getting this error on MacOS when trying to reproduce.
> 
> <img alt="Image" width="56" height="48" src="https://private-user-images.githubusercontent.com/10458212/515447658-283d2b4d-ddd5-4ab5-bee2-1d0df864f2e7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM0MjY5NzAsIm5iZiI6MTc2MzQyNjY3MCwicGF0aCI6Ii8xMDQ1ODIxMi81MTU0NDc2NTgtMjgzZDJiNGQtZGRkNS00YWI1LWJlZTItMWQwZGY4NjRmMmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE4VDAwNDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhY2E4OWU0NDUxNmJlNjk0YzExODdkOTkxMzQ5NGU3Y2JkMGRhN2QzNWQ4MDIxNTI0NGFkYTA3YzBiMDBjNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r_ZxitZDKOeo4CdnAUnfS37YyO1ht9h-ll5KMvzoAbs">
> Your screenshots don't show ] so maybe entirely unrelated! I'll ask the team to review the PR asap.

I think it's unrelated, though i don't see which place had the error in the screenshots. I went back and edited out the `type: stdio` step 3 in reproduce since zed doesnt use it, so that might fix it, the original was straight out of jetbrains settings and was more general. Either way though, the error in "actual behavior" screenshot points to line 5 column 20 which is exactly where the backslash is so i am pretty confident that's the main issue. Try it one more time without the `type: "stdio"`. It also might have another failure on macos since the path format may go under some validation when going into pathbuf for the os, but i don't remember the implementation offhand here.

**Comment by adam-huganir** [comment]
> > Just want to check...
> > What you pasted in is wrongly using ] vs } it seems and I'm getting this error on MacOS when trying to reproduce.
> > <img alt="Image" width="56" height="48" src="https://private-user-images.githubusercontent.com/10458212/515447658-283d2b4d-ddd5-4ab5-bee2-1d0df864f2e7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM0MjY5NzAsIm5iZiI6MTc2MzQyNjY3MCwicGF0aCI6Ii8xMDQ1ODIxMi81MTU0NDc2NTgtMjgzZDJiNGQtZGRkNS00YWI1LWJlZTItMWQwZGY4NjRmMmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE4VDAwNDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhY2E4OWU0NDUxNmJlNjk0YzExODdkOTkxMzQ5NGU3Y2JkMGRhN2QzNWQ4MDIxNTI0NGFkYTA3YzBiMDBjNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r_ZxitZDKOeo4CdnAUnfS37YyO1ht9h-ll5KMvzoAbs">
> > Your screenshots don't show ] so maybe entirely unrelated! I'll ask the team to review the PR asap.
> 
> I think it's unrelated, though i don't see which place had the error in the screenshots. I went back and edited out the `type: stdio` step 3 in reproduce since zed doesnt use it, so that might fix it, the original was straight out of jetbrains settings and was more general. Either way though, the error in "actual behavior" screenshot points to line 5 column 20 which is exactly where the backslash is so i am pretty confident that's the main issue. Try it one more time without the `type: "stdio"`. It also might have another failure on macos since the path format may go under some validation when going into pathbuf for the os, but i don't remember the implementation offhand here.

oh duh, my bad, i had just pasted the config block for a generic mcp, not the exact representation for the zed. i updated the code (it didn't have the required top level key (exactly one, hence the error message) in the description to match the screenshots. that should allow you to reproduce it with just copy paste 👍

**Comment by franciskafyi** [comment]
<img width="545" height="454" alt="Image" src="https://github.com/user-attachments/assets/59567e19-6c4c-40c3-9411-c9f6dfc3d794" />

I get this error now!

**Comment by adam-huganir** [comment]
> <img alt="Image" width="54" height="45" src="https://private-user-images.githubusercontent.com/10458212/515963357-59567e19-6c4c-40c3-9411-c9f6dfc3d794.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM2NTM0MDUsIm5iZiI6MTc2MzY1MzEwNSwicGF0aCI6Ii8xMDQ1ODIxMi81MTU5NjMzNTctNTk1NjdlMTktNmM0Yy00MGMzLTk0MTEtYzlmNmRmYzNkNzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTIwVDE1MzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkY2JlMjUyNjIyZDRjMzk4YmE2MWFhNmE5YWZlYTczYmVkOGRlOTlhY2NlYjQ4NTNkZDJhZGE5ODBiMjQ1NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZlTCHIg_oSuhcWzox36LxRagXpfdPODImDzk0Q19NmU">
> I get this error now!

my bad @franciskafyi, i swear i actually did it myself this time and recreated and didnt just rely on my (lacking) proofreading skills. this is the correct snippet which is actually valid json:

```json
{
  "some-mcp-server": {
    "env": {
      "IJ_MCP_SERVER_PORT": "64342"
    },
    "command": "C:\\Users\\adam\\AppData\\Local\\Programs\\PyCharm Professional\\jbr\\bin\\java",
    "args": [
      "-classpath",
      "C:\\Users\\adam\\AppData\\Local\\Programs\\PyCharm Professional\\plugins\\mcpserver\\lib\\mcpserver-frontend.jar;C:\\Users\\adam\\AppData\\Local\\Programs\\PyCharm Professional\\lib\\util-8.jar;C:\\Users\\adam\\AppData\\Local\\Programs\\PyCharm Professional\\lib\\modules\\intellij.libraries.ktor.client.cio.jar;C:\\Users\\adam\\AppData\\Local\\Programs\\PyCharm Professional\\lib\\lib-client.jar;C:\\Users\\adam\\AppData\\Local\\Programs\\PyCharm Professional\\lib\\modules\\intellij.libraries.ktor.client.jar",
      "com.intellij.mcpserver.stdio.McpStdioRunnerKt"
    ]
  }
}
```

once you click `add server`, it will spin on "Waiting for Context Server" but you should be able to hit `esc` to get out of it without waiting for it to time out. then when you click the little config wheel under "some-mcp-server" it should show you the original reported error

**Comment by franciskafyi** [comment]
<img width="538" height="194" alt="Image" src="https://github.com/user-attachments/assets/20bbac70-96c6-489a-948a-cce5b6299263" />

I got this the first time. And after that I get the "waiting for Context Server" like you mention. Can you send me the documentation to the MCP server you're trying to add? I think it's still a problem with the config and not with Zed (although I'm on MacOS so could be Windows specific but given I'm seeing the same thing it's probably not).

**Comment by adam-huganir** [comment]
> <img alt="Image" width="538" height="194" src="https://private-user-images.githubusercontent.com/10458212/516995068-20bbac70-96c6-489a-948a-cce5b6299263.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM2NjEyMDMsIm5iZiI6MTc2MzY2MDkwMywicGF0aCI6Ii8xMDQ1ODIxMi81MTY5OTUwNjgtMjBiYmFjNzAtOTZjNi00ODlhLTk0OGEtY2NlNWI2Mjk5MjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTIwVDE3NDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2N2ZmMDcxYmMwYWRiMzdkNDE0ODRkZjk3N2Q3YmVjN2Y3NTNmNGQzMmQwZWI3M2RiN2ZlMDZlMjMwMDQzMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t5fF2Ci_5iDxiZ413LXMMPW4WuBsoJ3mP6-x8FS1eic">
> I got this the first time. And after that I get the "waiting for Context Server" like you mention. Can you send me the documentation to the MCP server you're trying to add? I think it's still a problem with the config and not with Zed (although I'm on MacOS so could be Windows specific but given I'm seeing the same thing it's probably not).

@franciskafyi You should be able to ignore it and still recreate the issue by hitting the gear and pulling it up again, lemme try to add a screen recording (tl;dr, "\U" etc isn't valid json, where the pr makes it "\\U" which is)

https://github.com/user-attachments/assets/8aab8674-599a-483e-aab8-58dd6fe648a5

**Comment by franciskafyi** [comment]
Ooooh, I think I'm only understanding this now. You don't want to see JSON basically:

<img width="564" height="348" alt="Image" src="https://github.com/user-attachments/assets/eae97fc8-99ec-4f2a-bcc3-8392934680dd" />

Is that right?

**Comment by adam-huganir** [comment]
> Ooooh, I think I'm only understanding this now. You don't want to see JSON basically:
> 
> <img alt="Image" width="564" height="348" src="https://private-user-images.githubusercontent.com/10458212/517002866-eae97fc8-99ec-4f2a-bcc3-8392934680dd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM2NjIzMDgsIm5iZiI6MTc2MzY2MjAwOCwicGF0aCI6Ii8xMDQ1ODIxMi81MTcwMDI4NjYtZWFlOTdmYzgtOTllYy00ZjJhLWJjYzMtODM5MjkzNDY4MGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTIwVDE4MDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ODhlMWJiMjBjNGJjMzVlYTk4ZDEzYmI4NDEzZTUxZWUwNTVjZTAwNDM0MTU1NTE2ZjM1ZjM0OGNkN2YwMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EEvPAINCDcW5XNSk1F9zP5NeQvT1BwH9RjfqsqGCnvM">
> Is that right?

It's not that, it's that the JSON that is produced when you go back into "configure server" is not the same as the JSON the user configured in the first place when it is definitely intended to be. its also actually invalid so you can't save any changes (without manually correcting the issue itself). 

unfortunately the only examples i can think of will cause that second error, but that one is unrelated and can be ignored since that's not a bug, it's an unrelated but correct issue.

whoever ends up catching this ticket should hopefully be familiar enough with json and the serde library to spot the issue quickly, and i'll keep an eye out here if there are more questions

edit: it's the last screen in the video, the error at the bottom preventing save "invalid escape at line 5 columnt 20"
