### ISSUE TITLE
Zed LSP extensions not loading/crashing in WSL2

### ISSUE THREAD

**Issue by Zorgatone** [zed-industries/zed#42873]
### Summary

Zed LSP extensions not loading/crashing in WSL2

### Description
I am trying to use Zed (v0.212.6) on Windows 10 (x86_64) and WSL2 (Ubuntu 26.04 x86_64) and various LSPs and/or extensions seem to load load/work correctly or crash.

Steps to reproduce:
1. Open a project in WSL2
2. Try to edit the code and see hints
3. Observe LSPs/extension logs

Example problems:
```
Language server codebook:

from extension "Codebook Spell Checker" version 0.2.5: Failed to read version file: No such file or directory (os error 44)
```

```
Language server vtsls:

failure while downloading and/or installing Zed managed Node.js, restart Zed to retry: error downloading Node binary tarball
```

```
Language server eslint:

downloading release from https://github.com/zed-industries/vscode-eslint/archive/refs/tags/release%2F2.4.4.tar.gz: error sending request for url (https://github.com/zed-industries/vscode-eslint/archive/refs/tags/release%2F2.4.4.tar.gz): client error (Connect): dns error: failed to lookup address information: Name does not resolve
```

```
Language server tailwindcss-language-server:

failure while downloading and/or installing Zed managed Node.js, restart Zed to retry: error downloading Node binary tarball
```

I checked that from within a WSL terminal/shell session I have the DNS working and I can access the web. From VSCode I can open projects and have the LSPs and extension work just fine, so it seems to be more of a Zed issue

**Expected Behavior**:
- LSPs and Extensions work in WSL2 and don't crash
**Actual Behavior**:
- LSPs and Extensions don't work in WSL2 or crash

### Zed Version and System Specs

Zed 0.212.6 
74924bc91865f111542ac6b1554231a0d3f66f89

Windows 10 (x86_64)
WSL2 (Ubuntu 25.10 x86_64)

**Comment by Zorgatone** [comment]
Not sure how to see more logs (can't find a `Zed.log`)

**Comment by franciskafyi** [comment]
Thank you for this! Can you find `zed: open log` from the command palette?

**Comment by franciskafyi** [comment]
How have you downloaded Node and what version are you on? Some of the issues seem related to Node at least.

**Comment by Zorgatone** [comment]
Hey sorry I will try again next week when I'll be on a windows machine again!

**Comment by Zorgatone** [comment]
In the meantime, I can confirm that opening a remote through SSH such as a linux machine through Orbstack (macOS Tahoe 26.1 25B78 aarch64 host, and Ubuntu 26.04 aarch64 guest) I can open a project and have the LSPs working (typescript project).

**Comment by Zorgatone** [comment]
> How have you downloaded Node and what version are you on? Some of the issues seem related to Node at least.

about the node version, I have one downloaded through https://volta.sh/

**Comment by localcc** [comment]
do you have a proxy/vpn running or non standard dns settings? can you curl/wget the url that gives the network error in the wsl terminal successfully?

**Comment by t-ricci-avatarux** [comment]
No I wasn't using a VPN, I had verified that WSL2 had internet access and could ping websites and download stuff.
I was using cloudflare 1.1.1.1 DNS instead of Google, but that was before today's outage so it shouldn't matter I think

**Comment by franciskafyi** [comment]
Maybe we fixed this but I believe using Volta was causing problems for other users 👀

**Comment by blopker** [comment]
I don't know if this is helpful, but I've been experimenting with Zed using SSH remote development (Orbstack VM running Ubuntu Plucky, on a macOS host). I've been trying Codebook and rust-analyzer.

These extensions actually seem to work for me, but the log info is odd compared to local development.

For example, for both local extensions the `Server Info` tab is as expected:

```
* Server: codebook (id 4)

* Binary: LanguageServerBinary {
    path: "/Users/blopker/Library/Application Support/Zed/extensions/work/codebook/codebook-lsp",
    arguments: [
        "--root=/Users/blopker/code/codebook",
        "serve",
    ],
    env: Some(
        {
// Env info
```

But for both remote extensions, the `Server Info` seems to be missing the Binary info (Codebook example, but similar to Rust):

```
* Server: codebook (id 3)

* Binary: Unknown

* Registered workspace folders:


* Capabilities: {
  "positionEncoding": "utf-16",
  "textDocumentSync": 1,
  "codeActionProvider": {
    "codeActionKinds": [
      "quickfix"
    ]
  },
  "executeCommandProvider": {
    "commands": [
      "codebook.addWord",
      "codebook.addWordGlobal"
    ]
  }
}

* Configuration: Unknown
```

Another odd thing, the logs aren't showing up under `Server Logs`, when using SSH. The only logs I get seem to be some kind of performance warning, but I don't think they are from the extension process. This is for both Codebook and Rust:

```
2025-11-18T15:15:01.217067765-08:00  WARN overly long loop turn took 105.536908ms (event handling took 94.459µs): Notification { method: "textDocument/didChange" }
```

Attaching Zed.log in case it's helpful.

[2025-11-18T15:14:44-08:00.log](https://github.com/user-attachments/files/23615490/2025-11-18T15.14.44-08.00.log)

**Comment by JerryHong08** [comment]
Same issue here on Windows 11 + WSL2 (mirrored network mode) with Zed 0.227.1.

## Root Cause

After extensive debugging, I believe the core problem is specific to the **remote server** (`zed-remote-server`) use case on Windows+WSL2, and is distinct from how the main Zed process handles environment variables.

When using Zed on Windows to open a WSL2 folder via SSH, Zed's Windows process spawns `zed-remote-server` inside WSL2 over SSH. This SSH session is initiated by the Windows-side Zed process, which has no knowledge of your WSL2 shell environment. As a result, the remote server process starts with a minimal environment — and crucially, **proxy variables (`HTTP_PROXY`, `HTTPS_PROXY`, etc.) set in `~/.zshenv` or `~/.zshrc` are never present** when the remote server makes its own outbound HTTP requests to download Node.js, language servers, and extensions.

This is confirmed by the remote server log (`~/.local/share/zed/logs/server-workspace-*.log`), which shows the shell environment capture only providing `PATH` to the process — proxy vars are absent despite being correctly set and verified in the interactive shell:

```
{"message":"(remote server) set environment variables from shell:/usr/bin/zsh, path:/usr/local/bin:..."}
```

All network requests from the remote server then go out with no proxy, hitting connection timeouts:

```
client error (Connect): operation timed out
```

This is why VS Code is unaffected — its remote extension tunnels everything through the Windows-side process, which uses the Windows system proxy. Zed's remote server makes outbound connections independently from within WSL2.

## Confirmed Workaround

Create a **WSL-side** `~/.config/zed/settings.json` (separate from the Windows-side Zed settings) with the proxy explicitly configured:

```json
{
  "proxy": "http://127.0.0.1:7890"
}
```

The remote server binary reads this config file directly from the WSL machine. After adding this and restarting the remote server (`pkill -f zed-remote-server`), Node.js downloads successfully and all LSPs start loading normally.

## Suggested Fix

The remote server should read `~/.config/zed/settings.json` on the remote machine and apply the `proxy` setting **before** making any outbound HTTP requests (it currently appears to attempt downloads before settings are fully applied on startup). Alternatively, the remote server could also inherit proxy vars from the shell environment the same way it inherits `PATH`.

**Environment:** Windows 11, WSL2 Ubuntu, mirrored network mode, Zed 0.227.1, zsh

**Comment by Sebi11** [comment]
Hi!
For me, the above fix for all LSP extensions doesn't work on Windows 11 with WSL 2 (even after restarting completly WSL and killing Zed), I still get the error:

> failure while downloading and/or installing Zed managed Node.js, restart Zed to retry: error downloading Node binary tarball

Do you know if I should change the "proxy" url, especially the port?
