### ISSUE TITLE
GPUI: Text color change on hover not working

### ISSUE THREAD

**Issue by LMHCNLI** [zed-industries/zed#43214]
### Summary

Hello, all! I tried to change the text color on hover, but it didn't take effect. The same code worked for the active state though.
Here is my code:
```rust
use gpui::{
    AppContext, Application, Bounds, Context, InteractiveElement, IntoElement, ParentElement,
    Render, StatefulInteractiveElement, Styled, Window, WindowBounds, WindowOptions, black, blue,
    div, green, px, red, rgb, size, white, yellow,
};

struct SomeText {}

impl Render for SomeText {
    fn render(&mut self, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        div().flex().flex_col().size_full().bg(rgb(0xF1F1F1)).child(
            div()
                .id("text-container")
                .flex()
                .bg(black())
                .text_color(red())
                .text_size(px(20.0))
                // The text should turn green when hovering here
                .hover(|style| style.bg(white()).text_color(green()))
                .active(|style| style.bg(yellow()).text_color(blue()))
                .child("Some text"),
        )
    }
}

fn main() {
    Application::new().run(|cx| {
        let bounds = Bounds::centered(None, size(px(500.), px(500.0)), cx);
        cx.open_window(
            WindowOptions {
                window_bounds: Some(WindowBounds::Windowed(bounds)),
                ..Default::default()
            },
            |_window, cx| cx.new(|_cx| SomeText {}),
        )
        .unwrap();
    });
}
```

### Zed Version and System Specs

GPUI: 0.2.2
OS: Windows 10.0.26200
Memory: 31.7 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics || Intel Corporation || 32.0.101.5972

**Comment by DreamDrunker** [comment]
i'm experiencing the same issue with m4 macos. also tried using .group() and .group_hover(). not work either.

**Comment by as-cii** [comment]
I believe this was fixed by #42852. Please, re-open if I am missing something. Thanks!

**Comment by LMHCNLI** [comment]
@as-cii I noticed the issue with the txet size, and I'm glad it's now fixed. However, that wasn't the main concern of this issue—though they might be caused by the same bug. Currently, the text color still doesn't change on hover. But I did notice someone is already working on this in #43324. Perhaps we can continue pushing that PR forward! Also, I don't have permission to reopen this issue…

> I believe this was fixed by [#42852](https://github.com/zed-industries/zed/pull/42852). Please, re-open if I am missing something. Thanks!
