### ISSUE TITLE
Unable to recognize the types and methods defined in global.d.ts

### ISSUE THREAD

**Issue by ZhengXiaowei** [zed-industries/zed#4393]
### Check for existing issues

- [X] Completed

### Describe the feature

Unable to recognize the types and methods defined in global.d.ts.

I have a `global.d.ts` file in the src directory, but when writing code in `*.ts` files, I cannot access the types and methods defined in `global.d.ts`.

e.g:
<img width="697" alt="image" src="https://github.com/zed-industries/community/assets/15809841/ddcf6529-0ffe-440c-9ff2-a0e1debb6023">
<img width="1226" alt="image" src="https://github.com/zed-industries/community/assets/15809841/6a8062e0-eeb8-4082-ab68-0e8798c06631">

**Comment by shellscape** [comment]
This is related to, and extends to declaring modules for custom file type recognition. the TS LS implementation doesn't seem to pick up on this. Consider a `declarations.ts` file:

```ts
declare module '*.graphql' {
  const GraphQL: string;

  // @ts-ignore
  export = GraphQL;
}

declare module '*.yml' {
  const Yaml: string;

  // @ts-ignore
  export = Yaml;
}
```

This provides instruction to TS that `.graphql` files and `.yml` files can be resolved when imported via e.g. `import typeDefs from './mutations.graphql';`

I've not been able to get Zed to recognize these imports as resolvable, and TS will always present an error that they cannot be resolved.

**Comment by medz** [comment]
> I dont think you should have to, but did you try restarting the language server (command palette > `editor: restart language server`) to see if it picked up the changes? Can you include an image of the project tree?

Your method works! But I have a question, why does the language server crash after a while?

I am using TypeScript + Vue now. Whenever I immerse myself in editing Vue files, the language server crashes after a while.

Before you gave this solution, I usually forced Zed to close by `CMD+Q` and reopen it to solve it.

Although your method works, it is too inefficient. Our users cannot always restart the language server frequently. I think Zed did something to cause the TypeScript and Vue language servers to crash and exit. Can we do it like VS Code, automatically restart after detecting the language server crash instead of telling the user nothing.

**Comment by shellscape** [comment]
@JosephTLyons we're a year old on this one mate. any chance we could get some eyeballs on it?

**Comment by smitbarmase** [comment]
This seems to be working on the latest Zed with [create-vue-app](https://github.com/vuejs/create-vue), without any additional configuration mentioned above.

Here’s the project I'm testing it on: https://github.com/smitbarmase/zed-issue-4393.  

Can you check if it's resolved in your project on the latest Zed?  

https://github.com/user-attachments/assets/b1841a10-6a59-4ad5-8b03-2f936a67909b

**Comment by shellscape** [comment]
@SomeoneToIgnore please reopen. This is still reproducible in large repositories. The TSLS does just fine with smaller projects but this bug starts creeping up on larger repos. While I cannot grant public access, I'd like to setup a call with the team to demo the issue and triage. 

cc @JosephTLyons

**Comment by maxbrunsfeld** [comment]
If someone could share a reproduction case for this, that would be very helpful.

**Comment by shellscape** [comment]
@maxbrunsfeld can we connect so I can demo the issue on the repo, and perhaps do some live triage? reachable on X with the same username or the email shown in this commit https://github.com/shellscape/jsx-email/commit/36e0bbead81c0fa35cee0888183a7ec5880ca394.patch
