### ISSUE TITLE
Can not open file in zed if filename include (1)

### ISSUE THREAD

**Issue by kouhe3** [zed-industries/zed#44962]
### Reproduction steps

on windows 11, right click `name(1).txt` then select Open in zed.

### Current vs. Expected behavior

zed open `name`

<img width="1170" height="613" alt="Image" src="https://github.com/user-attachments/assets/3197cb27-f8e5-40b8-b8d2-faf6f56a431c" />

### Zed version and system specs

Zed Nightly 0.218.0 
a1dbfd0d777615cbe83b75dfd5237bb392b20631

0.218.0+nightly.2012.a1dbfd0d777615cbe83b75dfd5237bb392b20631

### If you are using WSL on Windows, what flavor of Linux are you using?

None

**Comment by miguelraz** [comment]
I can confirm it used to work on Zed stable (v0.216.1) and is broken in Preview (v0.217.1+preview.96.47f6dfd7).

**Comment by HactarCE** [comment]
I'm unable to reproduce this on macOS or Windows with Zed 0.217.1 stable with `~\Downloads\file(1).txt`. @miguelraz was there anything special you have to do to get it to break?

**Comment by miguelraz** [comment]
~~Ha, broken on stable, fixed in Preview~~

Hmmm, I can repro this, but non-deterministically:

https://github.com/user-attachments/assets/54244bfb-6b09-4c71-935e-b0ee7aadfa9c

**Comment by amtoaer** [comment]
I can reproduce this issue: if I try to use Zed to open "xxx(2).txt", edit and save it, it pops up an error and eventually saves to "xxx".

https://github.com/user-attachments/assets/62892888-80ff-4f8e-9ed1-9f6f43be504b

Furthermore, using `Open with Zed` to open "xxx(2).txt" when a Zed window is already open does not trigger this issue.

https://github.com/user-attachments/assets/203e6b41-ad3e-4efc-b9c2-bfae71de47bd

**Comment by HactarCE** [comment]
Thank you for the details! I was able to reproduce this on Windows with `file(1).txt` when Zed is not already open. I'll investigate further.

**Comment by HactarCE** [comment]
That PR doesn't fix this issue. I'm still able to reproduce it on `main`.

The problem is that `canonicalize()` isn't being called.
