### ISSUE TITLE
Hard to distinguish constant names and string values in some themes

### ISSUE THREAD

**Issue by liebkne** [zed-industries/zed#4617]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In some themes, constant names and strings use the same faces which make code hard to read.

### Environment

Zed: v0.96.0 (preview)
OS: macOS 13.2.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1072" alt="image" src="https://github.com/zed-industries/community/assets/5475262/d1f37887-56bc-4ae0-987b-e66de44db10a">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by failable** [comment]
Still happens in 

```
Zed: v0.154.1 (Zed Preview)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: x86_64
```

**Comment by JosephTLyons** [comment]
Thanks for testing and validating a bunch of these old bugs for us @failable!

**Comment by failable** [comment]
Still happens in

```
Zed: v0.172.5 (Zed Preview)
OS: macOS 15.1.0
Memory: 64 GiB
Architecture: aarch64
```

<img width="1027" alt="Image" src="https://github.com/user-attachments/assets/112f6440-4fd6-48a7-b411-c73c70eb4102" />

**Comment by notpeter** [comment]
I am able to reproduce, but not with any of the currently shipping default themes.
The Zed themes where this was the case have been deprecated:
https://github.com/zed-extensions/legacy-themes

This sort of thing is why they were ultimately removed from the default install -- it was extremely difficult to maintain/test all of the changes across dozens of default themes which resulted in a sub par experience.

Thanks for reporting.

**Comment by failable** [comment]
> I am able to reproduce, but not with any of the currently shipping default themes.

Hello, I am not sure what do you mean. Isn't the `One` light theme builtin? The issue happens for the `One` light theme. Can you paste a screenshot of how it is looked like in your Zed?

The Python highlighting is [broken](https://github.com/zed-industries/zed/issues/25803) since last week

<img width="270" alt="Image" src="https://github.com/user-attachments/assets/44857072-382e-4746-b39e-8469256df628" />

The fix will be launched next week.

but I believe this issue still exists for the `One` light theme.

**Comment by notpeter** [comment]
Here is the behavior for Zed Stable (176) and Preview (177) in One Light.

<img width="563" alt="Image" src="https://github.com/user-attachments/assets/f8c0b745-8a79-42b3-aa52-95dc40c9be67" />

Is my reproduction code wrong in some way?

I believe there may need to be updates to reflect those Python changes (either renaming of the queries, or adding additional syntax colors to the themes) in main/Nightly but what you are describing appears to have been fixed in One Light (it was definitely broken in most of the other deprecated themes).

I've reopened for the regression in 178:
- https://github.com/zed-industries/zed/issues/25709

**Comment by failable** [comment]
@notpeter I've update to 178, but the global variable names and strings are still have the same colors in the `One` theme.

<img width="410" alt="Image" src="https://github.com/user-attachments/assets/c5d202ca-8fa3-458c-9d67-7cf438eb94f6" />

It's hard to tell how many global variables at the first glance...

<img width="1024" alt="Image" src="https://github.com/user-attachments/assets/ab48cf69-5d99-46cb-8e4a-92986f7c61a5" />

**Comment by notpeter** [comment]
This is old, but it is expected.

This is not a python f-string, but another templating language.  As far as Python and tree-sitter is concerned, this is a regular string that the templating engine will process as a regular string.  You are looking for tree-sitter-python to be able to detect the injection of an arbitrary unspecified templating language inside standard strings.

<img width="264" alt="Image" src="https://github.com/user-attachments/assets/b8e6fafa-00e9-4fc4-88fa-2967a2dcedeb" />
