### ISSUE TITLE
Language server stuck in `Checking for updates for <lang> language server` status

### ISSUE THREAD

**Issue by baspinarenes** [zed-industries/zed#4628]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I downloaded Zed and entered my workspace. The status bar was shown the download log of the typescript and json language servers. Then the "Checking for updates to TSX language server" log was shown and it's not progressing. When I look at the Zed's language folder, the contents of the folders are empty. I have deleted folders multiple times and tried again but I am still in the same place.

### Environment

Zed: v0.94.4 (stable)
OS: macOS 13.3.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

```
$ ls -la ~/Library/Application\ Support/Zed/languages/json-language-server
total 0
drwxr-xr-x@ 2 enes.baspinar  staff   64 Jul 13 08:30 .
drwxr-xr-x@ 6 enes.baspinar  staff  192 Jul 13 08:30 ..

$ ls -la ~/Library/Application\ Support/Zed/languages/typescript-language-server
total 0
drwxr-xr-x@ 2 enes.baspinar  staff   64 Jul 13 08:37 .
drwxr-xr-x@ 6 enes.baspinar  staff  192 Jul 13 08:30 ..
```

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/community/files/12035784/Zed.log)

**Comment by yocontra** [comment]
Still an issue as of latest release today with TS + TSX servers. Running this fixed it for me:

```sh
rm -rf ~/package-lock.json ~/package.json ~/node_modules
npm cache clean --force
```

+ a reboot of zed.

**Comment by ForLoveOfCats** [comment]
Thanks to an awesome community contribution this issue should now be fixed for Node-based language servers! Please let us know if you continue to experience this issue once the fix goes out in a release :)

**Comment by div002123** [comment]
Why do people continue to use Zed despite this fatal bug?

**Comment by murdahl** [comment]
Hey, I'm having the same issue now with the CSharp language server, and there are no rouge files in my home directory.

**Comment by zxch3n** [comment]
It is still happening on Rust
![CleanShot 2024-03-14 at 16 40 46@2x](https://github.com/zed-industries/zed/assets/18425020/dd34a3e8-7c71-4e4d-b8a5-5e1c65bc9cdf)

Related logs

```
2024-03-14T16:38:48+08:00 [INFO] fetching latest version of language server "rust-analyzer"
2024-03-14T16:38:48+08:00 [ERROR] failed to start language server "rust-analyzer": status error 403, response: "{\"message\":\"API rate limit exceeded for 172.234.90.111. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n"
2024-03-14T16:38:48+08:00 [ERROR] server stderr: Some("")
2024-03-14T16:38:48+08:00 [ERROR] Hit 4 reinstallation attempts for "rust-analyzer"
```

Zed 0.126.2

**Comment by AdamSchinzel** [comment]
> I got around this for typescript by manually cloning and building the typescript-language-server repo:
> 
> 1. Quit Zed completely
> 2. Delete `~/Library/Application\ Support/Zed/languages/typescript-language-server`
> 3. `git clone git@github.com:typescript-language-server/typescript-language-server.git ~/Library/Application\ Support/Zed/languages/typescript-language-server`
> 4. *`cd ~/Library/Application\ Support/Zed/languages/typescript-language-server && rm yarn.lock && yarn && yarn build`
> 5. Start Zed
> 
> * In 4 I delete the `yarn.lock` file because yarn wouldn't install with the repo's lockfile 🤷
> 
> Edit: Similar for json: follow 1 & 2 from above 3. `git clone git@github.com:zed-industries/json-language-server.git ~/Library/Application\ Support/Zed/languages/json-language-server` 4. `cd ~/Library/Application\ Support/Zed/languages/json-language-server && ./script/build`

Happened to me today with TypeScript and this help. I assume this will help with any language server. I guess Zed is still to early for anyone that is not willing to find these solutions.

**Comment by krischal111** [comment]
I had the Zig extension installed but features like code autocompletions were not working. Apparently installing the Zed's CLI fixed the issue.

**Comment by Umckgil** [comment]
this issue happens to me for the lua language server
