### ISSUE TITLE
Multi-cursor "drag" is not working

### ISSUE THREAD

**Issue by wgordon17** [zed-industries/zed#6423]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The [features page](https://zed.dev/features#multi-cursor-editing) describes multi-cursor editing as being available with

> the mouse by alt-clicking/dragging

I am successfully able to hold the "option" key and click in several places to get multiple cursors, however _holding_ the "option" key and dragging the mouse performs a "normal" select operation, and does not create multiple cursors.

### Environment

Zed: v0.118.1 (Zed)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @wgordon17, what happens if you hold down `shift-opt`, then start your drag?

**Comment by wgordon17** [comment]
@JosephTLyons that _definitely_ helps, adding in `shift`. This is definitely an improvement, but it's still slightly..._off_ from my expectations. `shift-opt` assumes that I want all cursors in the same column, but if I'm trying to drag-to-add multi-cursors at the _end_ of all lines, then things go weird. If I start on a line that's too long, it'll just skip the shorter lines altogether. And if I start on a line that's too short, then it will select the text that's longer while also placing the cursor at the end of the line

**Comment by orthotypos** [comment]
@wgordon17 are you maybe using some window manager like yabai?
If yes, this would hijack alt + click so you would have to either disable that in yabai config or rebind alt + click behavior in zed config to some other key combo.

**Comment by ipearx** [comment]
This thwarted me to, I'd expect it to behave like Sublime:

- Dragging vertically while holding option should add multiple cursors
- Dragging vertically while holding option past the end of multiple lines should put multiple cursors at the end of the line
- Dragging while holding option diagonally should add multiple cursors and select the region

One thing that sublime does that's annoying that could be an improvement:

- I use line wrap on most of the time, it would be great if the multi-cursor select could skip the wrapped lines, i.e. treat them like they aren't wrapped. I may be asking for the impossible here...

**Comment by wgordon17** [comment]
Still reproducible

**Comment by omergoktas** [comment]
> Hey @wgordon17, what happens if you hold down `shift-opt`, then start your drag?

Why do we have to press `shift` additionally to drag and select multiple lines? Why simply pressing `alt` is not enough? I can't even modify this weird behavior. My settings are as follows:

    {
      // The key to use for adding multiple cursors
      // Currently "alt" or "cmd_or_ctrl"  (also aliased as
      // "cmd" and "ctrl") are supported.
      "multi_cursor_modifier": "alt"
    }

See? -it is not `alt+shift` or something; it's just `alt`. Plus, look at this other weird behavior; when the cursor is at the end of the line, the multiline drag assumes that I want to start selecting from the end of the line instead of where I click on to start dragging:

https://github.com/user-attachments/assets/ec754d66-7216-44d4-b7f5-ddb5614b458f

There are two separate bugs as far as I am concered. Pressing `shift` should not be mandatory, and the multiline selection should start from where I click on.

Also, `multi_cursor_modifier` setting is not even documented [here](https://zed.dev/docs/configuring-zed); just so you know.

Thanks in advance, and sorry if I was mistaken at anything.

**Comment by firecall** [comment]
I still have the two issues as described by @omergoktas. 

1) Being able to define key bindings to Option + Click and Drag to to select multi cursors. 
Currently you have to use Option + Shift + Click and Drag. 

2) If you do Option + Shift + Click and Drag at the end of a line, you get unexpected behaviour. 

My mental map for this is that it should work as it does in Sublime Text. 

I'd like to give ZED a decent go, but this issue drives me bonkers!

**Comment by malomalo** [comment]
I also have this issue and have a hard time moving to Zed with it.

I don't see why `alt+drag` doesn't behave as expected ala TextEdit / TextMate / Sublime. `alt+click` can still be select multiple cursors. I would really like this option. If it is not an options being able to reconfigure the current `shift+alt+drag` to `alt+drag` and the current `alt+click` to anything else

**Comment by cnlinjie** [comment]
I also have this issue and have a hard time moving to Zed with it.

**Comment by timwedde** [comment]
Kept running into this and was annoyed enough with this unexpected (and seemingly unchangeable?) behavior to dig through the GitHub issues, so here I am. Want to add another voice to this to hopefully get it resolved in some way.

**Comment by bemky** [comment]
+1
still happening in Zed 0.191.7

**Comment by bcdrew** [comment]
Still happening in 0.197.0

**Comment by smitbarmase** [comment]
After recent work on editor selections, we now support all mouse-driven selection behaviors that other editors do. Few keybindings are different and still hard to tweak, but we’ll be working to make them as configurable as possible. For now check out [multi-cursor-modifier setting](https://zed.dev/docs/configuring-zed?highlight=mouse#multi-cursor-modifier) to switch between `cmd` and `opt`.

If you have suggestions for better defaults, please open a discussion and tag this issue.

Closing this as resolved. 

| Action                                                                 | Zed                         | Sublime            | VS Code                        |
|------------------------------------------------------------------------|-----------------------------|--------------------|--------------------------------|
| Extend existing selection                                              | Shift + Click/Drag          | Shift + Click/Drag | Shift + Click/Drag             |
| Multiple selections anywhere                                           | Opt + Click/Drag            | Cmd + Click/Drag   | Opt + Click/Drag               |
| Go to definition                                                       | Cmd + Click                 | ??                 | Cmd + Click                    |
| Columnar selection from mouse position                                 | Cmd + Shift + Drag          | Opt + Drag         | N/A                  |
| Selections at end of line                                              | Cmd + Shift + Drag          | Opt + Drag         | N/A                  |
| Multi-cursor in straight line (every line; cursor at end of shorter)   | Cmd + Shift + Drag          | Opt + Drag         | Opt + Shift + Drag             |
| Multi-cursor in straight line with skipping (shorter lines are skipped)| Opt + Shift + Click/Drag    | ??                | ??                             |
| Columnar selection from cursor                                         | Opt + Shift + Click/Drag    | Not supported      | Opt + Shift + Click/Drag       |

**Comment by omergoktas** [comment]
https://github.com/zed-industries/zed/issues/6423#issuecomment-2564361695

The problems I outlined in the above comment are still happening even in 0.199.6 (the latest version of zed as of right now).

1. I still have to press `shift` in addition to `alt` to start multi-select (pressing `alt` is not enough).
2. If the cursor in the editor is at the end of a line and I start multi-select, it selects the wrong area.

Read the comment I just referenced and watch the video for yourself.

Nothing is fixed, just sayin'...

**Comment by smitbarmase** [comment]
1. I mentioned we need to improve keybind configuration for this. The original issue was about the cursor not creating multiple cursors, which is now possible it's just with a different keybind. You can create a separate issue for better mouse selection configuration if you’d like to track it, but it’s already on our radar. Thanks for being patient.

2. I think your comment is from last year. What you’re trying to do in the video is “Columnar selection from cursor,” which was already in Zed at the time, same as in VSCode. Since then, we’ve added “Columnar selection from mouse position,” which gives a more Sublime-like columnar selection. 

See PRs:

- https://github.com/zed-industries/zed/pull/31888
- https://github.com/zed-industries/zed/pull/32779
