### ISSUE TITLE
"Typescript-language-server" failed to execute npm install

### ISSUE THREAD

**Issue by nermalcat69** [zed-industries/zed#7373]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```
Language server error: TSX

failed to execute npm install subcommand:
stdout: ""
stderr: "npm ERR! code E404\nnpm ERR! 404 Not Found - GET https://registry.npmjs.org/nermal-cli-starter/-/nermal-cli-starter-0.0.1.tgz - Not found\nnpm ERR! 404 \nnpm ERR! 404  'nermal-cli-starter@https://registry.npmjs.org/nermal-cli-starter/-/nermal-cli-starter-0.0.1.tgz' is not in this registry.\nnpm ERR! 404 \nnpm ERR! 404 Note that you can also install from a\nnpm ERR! 404 tarball, folder, http url, or git url.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/arjunaditya/Library/Application Support/Zed/node/node-v18.15.0-darwin-x64/cache/_logs/2024-02-05T10_27_51_458Z-debug-0.log\n"
```

**To Reproduce**
1. `cmd + shift + p` and install cli and check the taskbar

### Environment

Zed: v0.120.6 (Zed)
OS: macOS 13.6.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="919" alt="image" src="https://github.com/zed-industries/zed/assets/73933669/18febc60-f158-41bc-9648-dbedee4df1cb">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

<img width="896" alt="image" src="https://github.com/zed-industries/zed/assets/73933669/f654e9c2-043f-4902-9baa-84f94579aad0">

**Comment by Dlutermade** [comment]
me too

**Comment by LilDojd** [comment]
Hey! Please check whether you have any stray `package.json` or `*.lock` files in your home directory. Removing them should solve the issue

**Comment by JosephTLyons** [comment]
Hey @nermalcat69 and @Dlutermade, can you download preview and see if your issues persists?

https://zed.dev/releases/preview

Thanks

**Comment by nermalcat69** [comment]
Hey @JosephTLyons, for suree thanks imma let you know

**Comment by notpeter** [comment]
Going through some old issues.

@nermalcat69 @Dlutermade are either of you still seeing this issue or is it ok to close?

**Comment by nermalcat69** [comment]
> Going through some old issues.
> 
> 
> 
> @nermalcat69 @Dlutermade are either of you still seeing this issue or is it ok to close?

Hey i'll get back to you asap

**Comment by notpeter** [comment]
I'm going to close. Feel free to reopen if the issue persists.  Thanks

**Comment by seakrebel** [comment]
Just got the same error
Using v0.157.5

Already tried uninstalling and installing the plugin, as well as disconnecting VPN in case this were the problem, but no luck.

![Screenshot 2024-10-22 at 09 40 22@2x](https://github.com/user-attachments/assets/80e56857-506c-44fb-afdb-7d8b4499a2ea)
