### ISSUE TITLE
Flickering project panel

### ISSUE THREAD

**Issue by rope-hmg** [zed-industries/zed#8598]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I updated. The release notes claim to be fixing a flickering UI, but I previously wasn't experiencing it.

I've seen some similar bugs being reported, but none of the others are for this specific bit of UI. I figured I'd report it just in case it's caused by something else.

### Environment

Zed: v0.124.7 (Zed)
OS: macOS 13.6.3
Memory: 96 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/2173098/38537edc-b67a-41b7-8780-6cb67532a4e2

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment]
The project panel contents getting covered seems reminiscent of https://github.com/zed-industries/community/issues/2387.

This doesn't initially appear to be the same as the flicking bug that was fixed (although it's possible that the temporary fix we put in place is now causing this issue to manifest).

**Comment by Congyuwang** [comment]
Exact same problem on:
```
Zed 0.124.8 0ec803cea977afad95f836bc869efd1016de8b8d,
macOS 14.3.1,
m2 chip.
```

It does not seem to always appear, but somehow accidentally triggered.

**Comment by rope-hmg** [comment]
After updating to `Zed: v0.124.8` I haven't seen it again, but since @Congyuwang is on the same version and said they've seen it I'll leave this open.

**Comment by Moshyfawn** [comment]
> After updating to `Zed: v0.124.8` I haven't seen it again, but since @Congyuwang is on the same version and said they've seen it I'll leave this open.

There's [another confirmation](https://github.com/zed-industries/zed/issues/8363#issuecomment-1979165656) that the problem still exists.

**Comment by varunneal** [comment]
Getting this as well, M4 Pro on Zed 0.208.6. Flickering is quite severe.
